### PR TITLE
Simplifications and minor improvements of HamiltonianCycleAlgorithms

### PR DESCRIPTION
**Pull request by HannesWell**
This PR contains some internal simplifications and minor improvements of the `HamiltonianCycleAlgorithm` implementations `PalmerHamiltonianCycle`, `TwoOptHeuristicTSP `and `NearestNeighborHeuristicTSP`:

- The `PalmerHamiltonianCycle` implementation was revised to use only one array of vertex-elements, mainly to make it more comprehensible. As secondary effect it should be a little faster and should require less memory.

- For `TwoOptHeuristicTSP` the VertexToIntegerMapping is used and the application of the 2-opt move (reversal of the segment between the cut edges) is done without full copy into a second array.

- `NearestNeighborHeuristicTSP` was revised to use only one array of vertex-elements which is also used as backing array of the vertex-List of the returned `GraphPath`.
Actually I expected a slight performance improvement by this change, but when I did some benchmarks unfortunately it turned out that the runtime is almost exactly the same as before.
Nevertheless I submit this change since the memory consumption is reduced by avoiding the `Set` of unvisited vertices and the second path-List. And I think for a lightweight algorithm like Nearest-Neighbor this is a little advantage.

----

- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/Become-a-Contributor>
- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/How-to-make-your-first-%28code%29-contribution>
- [x] I added [unit tests](https://github.com/jgrapht/jgrapht/wiki/Unit-testing)
- [x] I added [documentation](https://github.com/jgrapht/jgrapht/wiki/How-to-write-documentation)
- [x] I followed the [Coding and Style Conventions](https://github.com/jgrapht/jgrapht/wiki/Coding-and-Style-Conventions)
- [x] I **have not** modified `HISTORY.md` or `CONTRIBUTORS.md`
- [x] I ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)

### CODE REVIEW

**Comment by HannesWell** [comment]
Do you have any remarks regarding this pull-request?

**Comment by jsichi** [comment]
@harmanpa @d-michail @AlexandruValeanu any comments on this one?

**Comment by harmanpa** [comment]
I'm happy with any change that improves memory consumption 👍

**Comment by HannesWell** [comment]
If you want I can split this PR into four smaller ones, to make the review easier:
One for the ArrayUtil class (I think there are some more use-cases in the library) and one for each of the changed algorithms (`TwoOptHeuristicTSP`, `NearestNeighborHeuristicTSP`, `PalmerHamiltonianCycle`).

The PR for the ArrayUtil would have to be merged first.

**Comment by jsichi** [comment]
Thanks!  I'm going to merge as is since there were no further review comments.

**Pull request merged**
