### PR TITLE
Use -noimport instruction to avoid import of own jgrapht-packages in MANIFEST.MF

### PR DESCRIPTION
**Pull request by HannesWell**
In order to solve issue #736 I proposed PR #952, which manually excludes all own (exported) packages of a jgrapht-module from the `Import-Package` instruction in its pom.xml.
Now I found a much simpler solution (thanks to the new Maven-Source for the Eclipse TargetPlatform).

Instead of the solution implemented in PR #952, the same result can be achieved by using the `-noimport` directive in the `Export-Package` instruction in the configuration of the `maven-bundle-plugin` in the root pom.xml.
This makes the exclusion of own packages in each module-pom obsolete and therefore simplifies the maintenance of JGraphT because.

In case new modules or packages that don't start with its module's name are added in the future, it shouldn't be necessary anymore to explicitly exclude them from being imported in the MANIFEST.MF. Self-importing should be completely disabled now.
See https://bnd.bndtools.org/heads/export_package.html for details.

I tested this solution and the MANIFEST.MF produced by the build are fine and equivalent to the current ones for all modules.

----

- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/Become-a-Contributor>
- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/How-to-make-your-first-%28code%29-contribution>
- [ ] I added [unit tests](https://github.com/jgrapht/jgrapht/wiki/Unit-testing)
- [ ] I added [documentation](https://github.com/jgrapht/jgrapht/wiki/How-to-write-documentation)
- [x] I followed the [Coding and Style Conventions](https://github.com/jgrapht/jgrapht/wiki/Coding-and-Style-Conventions)
- [x I **have not** modified `HISTORY.md` or `CONTRIBUTORS.md`
- [x] I ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)

### CODE REVIEW

**Comment by jsichi** [comment]
@d-michail can you take a look?

**Comment by d-michail** [comment]
I have not tested it myself, but I agree that it looks cleaner.

**Comment by HannesWell** [comment]
What I did for testing was to build the jars for all modules first and then unzipped each in another co-located folder. Then repeated it with the state before the commit (using another container-folder) and finally run a diff on the folders of the two versions.

The only thing different was the timestamp in the Manifests.

**Comment by d-michail** [comment]
Thanks for the clarification. 

@jsichi If you also agree, this looks fine.

**Comment by jsichi** [comment]
Looks good to me too, thanks!

**Pull request merged**
