### PR TITLE
Preparations for the 1.2.1 release cycle

### PR DESCRIPTION
**Pull request by jkinable**
- Removed all deprecated code
- I disabled various tests in the `BergeGraphInspectorTest` class. These tests took forever to complete on my system. We need to decide what to do with them. I wouldn't throw them away, but certainly not include them in the normal test cycle. See issue #579 
- Some of the getGraph/setGraph methods in the cycle package have been deprecated in the previous release, others have not. Currently I've only removed  the methods which were deprecated. For consistency I would propose to deprecate all getGraph/setGraph methods in the cycle package, and provide the graph as a constructor parameter

### CODE REVIEW

**Comment by jkinable** [comment]
When running `mvn javadoc:aggregate` I noticed this in the output:
[INFO] --- maven-javadoc-plugin:3.0.0:aggregate (default-cli) @ jgrapht ---
[ERROR] no module descriptor for org.jgrapht:jgrapht
[ERROR] no module descriptor for org.jgrapht:jgrapht-core
[ERROR] no module descriptor for org.jgrapht:jgrapht-io
[ERROR] no module descriptor for org.jgrapht:jgrapht-ext
[ERROR] no module descriptor for org.jgrapht:jgrapht-guava
[ERROR] no module descriptor for org.jgrapht:jgrapht-demo
[ERROR] no module descriptor for org.jgrapht:jgrapht-dist
Does not seem to be harmful, but need to see where this comes from.

**Comment by jkinable** [comment]
Alright, the preparations for the new release cycle should be finished. Please merge this PR before any other PR...

**Comment by jsichi** [comment]
Regarding the missing module descriptors, it's probably fallout from #458 and will go away once we add the module-info.java files.

**Comment by jsichi** [comment]
@d-michail since you had several special-case deprecations this time around, can you take a look and then merge if they're all resolved?

**Comment by d-michail** [comment]
Thanks! Unit tests to the rescue!

**Pull request merged**
