### PR TITLE
Fail on javac warnings

### PR DESCRIPTION
**Pull request by koppor**
[Dev guide: Contributor Guidelines](https://github.com/jgrapht/jgrapht/wiki/Dev-guide%3A-Contributor-Guidelines):

> Unfortunately, there is no way to get the build to stop on warnings for javac and javadoc, so please scan the output carefully. (If you know of a way to fix this, please contribute a buildfile change.)

Here you go.

- JavaC hint is from the question https://stackoverflow.com/q/9192613/873282
- JavaDoc always fails since Java 1.8. See https://stackoverflow.com/a/16743137/873282

----

- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/Become-a-Contributor>
- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/How-to-make-your-first-%28code%29-contribution>
- [ ] I added [unit tests](https://github.com/jgrapht/jgrapht/wiki/Unit-testing)
- [ ] I added [documentation](https://github.com/jgrapht/jgrapht/wiki/How-to-write-documentation)
- [x] I followed the [Coding and Style Conventions](https://github.com/jgrapht/jgrapht/wiki/Coding-and-Style-Conventions)
- [x] I **have not** modified `HISTORY.md` or `CONTRIBUTORS.md`
- [x] I ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)

### CODE REVIEW

**Comment by jsichi** [comment]
Hmm, when I tried introducing a spurious warning, this didn't catch it.  After trying a few things, it seems like this works:

```
					<configuration>
					  <release>11</release>
                                          <compilerArgs>
					    <arg>-Xlint:all</arg>
					    <arg>-Werror</arg>
                                          </compilerArgs>
					</configuration>
```

With that setting, it catches some existing warnings which we'll need to fix before enabling this.

**Comment by d-michail** [comment]
I do not really thing we need this. The Javadoc causes a lot of problems with cross jdk builds. I remember adding a `nolint` option in order to build the project with new openjdks.

**Comment by koppor** [comment]
Maybe, disable the JavaDoc linting?

Enable the compiler warnings (`javac) would be a good thing.

Not sure whether [ErrorProne](https://github.com/google/error-prone) would be too much. - I can submit a PR (or just link a branch in my repo) if you want to investigate it.

**Comment by d-michail** [comment]
Yes, I have already disabled linting. javac warning are indeed ok, but we have a few warnings here and there which need to be fixed first.

**Comment by jsichi** [comment]
Yes, for this PR, let's focus on getting the javac warnings fixed and enforced.

Regarding ErrorProne, we have had attempts with other static analyzers in the past which didn't go anywhere.  The criteria for configuring+adding it are 

(a) finds significant quantity of real problems, making maintenance worthwhile 
(b) doesn't flag so many spurious issues that it becomes annoying 
(c) all existing code is brought into conformance before enablement
(d) enforceable (not just warnings, otherwise no one will look at it)

**Comment by jsichi** [comment]
Closing this out, replaced by #946.

**Pull request closed without merging**
