### PR TITLE
Submodule jgrapht-io

### PR DESCRIPTION
**Pull request by d-michail**
Separated the importers/exporters from the visualization adapters.

  - Moved all importers/exporters into org.jgrapht.io
  - Moved all importers/exporters into jgrapht-io submodule
  - Deprecated all importers/exporters in org.jgrapht.ext

Submodule jgrapht-ext has jgrapht-io as a dependency in order to avoid breaking current builds.

This change allows users to use importers/exporters without the dependency on the various visualization libraries.

### CODE REVIEW

**Comment by jkinable** [comment]
Looks good to me, although I am certainly no expert in mvn based stuff. In fact, mvn has always been very obscure to me. If you have any recommended reading material to improve my understanding of mvn, then I'm happy to hear about it.
- After moving the IO code to the IO package, shouldn't the pom.xml in the ext package be simplified? There seems to be quite a bit of code related to antlr in there.
- Are we planning to remove the dependency on the IO package from the EXT package in the next release?

**Comment by d-michail** [comment]
I removed all antlr and xml parsers from the EXT package. Now the deprecated classes delegate to the classes in the IO package.

Indeed, after the next release (and removal of deprecated classes in org.jgrapht.ext) the dependency from the EXT to the IO package will be redundant.

**Comment by jkinable** [comment]
Great, thanks. Looks ready to me. Let's see whether @jsichi wants to add something, otherwise this can be merged.

**Comment by jsichi** [comment]
Looks fine to me.  I was going to ask why we need an uber jar for io, but then I remembered that it has the antlr dependency, so that makes sense.

**Comment by jkinable** [comment]
First merge of the next version. Keep them coming :)

**Pull request merged**
