### PR TITLE
Proposed Eclipse formatter settings for JGraphT 1.0 release.

### PR DESCRIPTION
**Pull request by jsichi**
Because the Eclipse formatter XML version changed, below is a diff which shows only the actual changes:

```
jvs@havnor:~/open/jgrapht-eclipse/etc$ diff original.xml updated.xml 
13c13
< <setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_package" value="insert"/>
---
> <setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_package" value="do not insert"/>
47c47
< <setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_parameter" value="insert"/>
---
> <setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_parameter" value="do not insert"/>
49c49
< <setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_field" value="insert"/>
---
> <setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_field" value="do not insert"/>
58c58
< <setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_method" value="insert"/>
---
> <setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_method" value="do not insert"/>
60c60
< <setting id="org.eclipse.jdt.core.formatter.alignment_for_parameterized_type_references" value="0"/>
---
> <setting id="org.eclipse.jdt.core.formatter.alignment_for_parameterized_type_references" value="16"/>
63c63
< <setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_enum_constant" value="insert"/>
---
> <setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_enum_constant" value="do not insert"/>
83c83
< <setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_local_variable" value="insert"/>
---
> <setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_local_variable" value="do not insert"/>
86c86
< <setting id="org.eclipse.jdt.core.formatter.alignment_for_union_type_in_multicatch" value="16"/>
---
> <setting id="org.eclipse.jdt.core.formatter.alignment_for_union_type_in_multicatch" value="32"/>
97c97
< <setting id="org.eclipse.jdt.core.formatter.alignment_for_arguments_in_explicit_constructor_call" value="48"/>
---
> <setting id="org.eclipse.jdt.core.formatter.alignment_for_arguments_in_explicit_constructor_call" value="32"/>
110,111c110,111
< <setting id="org.eclipse.jdt.core.formatter.alignment_for_parameters_in_constructor_declaration" value="48"/>
< <setting id="org.eclipse.jdt.core.formatter.alignment_for_type_parameters" value="0"/>
---
> <setting id="org.eclipse.jdt.core.formatter.alignment_for_parameters_in_constructor_declaration" value="32"/>
> <setting id="org.eclipse.jdt.core.formatter.alignment_for_type_parameters" value="16"/>
113c113
< <setting id="org.eclipse.jdt.core.formatter.alignment_for_arguments_in_method_invocation" value="48"/>
---
> <setting id="org.eclipse.jdt.core.formatter.alignment_for_arguments_in_method_invocation" value="32"/>
119c119
< <setting id="org.eclipse.jdt.core.formatter.insert_new_line_at_end_of_file_if_missing" value="do not insert"/>
---
> <setting id="org.eclipse.jdt.core.formatter.insert_new_line_at_end_of_file_if_missing" value="insert"/>
124c124
< <setting id="org.eclipse.jdt.core.formatter.alignment_for_expressions_in_array_initializer" value="48"/>
---
> <setting id="org.eclipse.jdt.core.formatter.alignment_for_expressions_in_array_initializer" value="16"/>
140c140
< <setting id="org.eclipse.jdt.core.formatter.alignment_for_assignment" value="0"/>
---
> <setting id="org.eclipse.jdt.core.formatter.alignment_for_assignment" value="16"/>
147c147
< <setting id="org.eclipse.jdt.core.formatter.alignment_for_conditional_expression" value="80"/>
---
> <setting id="org.eclipse.jdt.core.formatter.alignment_for_conditional_expression" value="16"/>
152c152
< <setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_type" value="insert"/>
---
> <setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_type" value="do not insert"/>
158c158
< <setting id="org.eclipse.jdt.core.formatter.alignment_for_arguments_in_allocation_expression" value="48"/>
---
> <setting id="org.eclipse.jdt.core.formatter.alignment_for_arguments_in_allocation_expression" value="32"/>
174c174
< <setting id="org.eclipse.jdt.core.formatter.alignment_for_resources_in_try" value="80"/>
---
> <setting id="org.eclipse.jdt.core.formatter.alignment_for_resources_in_try" value="32"/>
177c177
< <setting id="org.eclipse.jdt.core.formatter.alignment_for_selector_in_method_invocation" value="80"/>
---
> <setting id="org.eclipse.jdt.core.formatter.alignment_for_selector_in_method_invocation" value="32"/>
214c214
< <setting id="org.eclipse.jdt.core.formatter.alignment_for_type_arguments" value="0"/>
---
> <setting id="org.eclipse.jdt.core.formatter.alignment_for_type_arguments" value="16"/>
240c240
< <setting id="org.eclipse.jdt.core.formatter.alignment_for_arguments_in_qualified_allocation_expression" value="48"/>
---
> <setting id="org.eclipse.jdt.core.formatter.alignment_for_arguments_in_qualified_allocation_expression" value="32"/>
256c256
< <setting id="org.eclipse.jdt.core.formatter.alignment_for_parameters_in_method_declaration" value="48"/>
---
> <setting id="org.eclipse.jdt.core.formatter.alignment_for_parameters_in_method_declaration" value="32"/>
291c291
< <setting id="org.eclipse.jdt.core.formatter.alignment_for_expressions_in_for_loop_header" value="0"/>
---
> <setting id="org.eclipse.jdt.core.formatter.alignment_for_expressions_in_for_loop_header" value="16"/>
```

(I obtained this by first exporting the latest settings with the latest XML version, and then re-exporting after making my changes.)

### CODE REVIEW

**Comment by jsichi** [comment]
@jkinable these are the formatter settings I'm proposing we use for the mass reformat.  They don't match Jalopy exactly, but they're close enough (and in some cases, such as the param/arg wrapping, I think they're actually an improvement).

Mass reformat will be done in a separate pull request (after we've merged all functional changes we want to include in the release).

**Comment by jkinable** [comment]
In general, this looks very nice. I would however prefer to increase the length of the lines. On modern high-res screens (usually wide-screen), the default width of 80 characters/line is very small. Most editors put the default to 120 or even 150. Could you set the line length to 120:
<setting id="org.eclipse.jdt.core.formatter.comment.line_length" value="120"/>
<setting id="org.eclipse.jdt.core.formatter.lineSplit" value="120"/>

I tried running the formatter in 2 ways:
1. Command line
2. Through the eclipse IDE (Eclipse Neon).
Strangely, I achieved **different** results depending on which method I used! When running through the command line, Eclipse seems to apply default settings which are different from the config file.  perhaps I'm doing something wrong.

To run the formatter using the command line:
`/opt/eclipse_neon/java_neon/eclipse/eclipse -vm /usr/lib/jvm/java-8-oracle/bin/java -application org.eclipse.jdt.core.JavaCodeFormatter -quiet -config ~/workspace/javaIDEA/jgrapht/etc/eclipse-formatter-settings.xml EdmondsKarpMFImpl.java`

To run the above command on every file:
`find . -name \*.java -print -exec /opt/eclipse_neon/java_neon/eclipse/eclipse -vm /usr/lib/jvm/java-8-oracle/bin/java -application org.eclipse.jdt.core.JavaCodeFormatter -quiet -config ~/workspace/javaIDEA/jgrapht/etc/eclipse-formatter-settings.xml {} \;`

**Comment by jkinable** [comment]
Ok, I found the issue. For some weird reason, the command line tool doesn't complain if it cannot parse a configuration file; instead, it applies some standard configuration. Turns out that the command line utility does NOT expect the nicely formatted xml config file. Instead, it needs a different format.
For details, refer to:

- http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftasks-231.htm
- http://help.eclipse.org/neon/topic/org.eclipse.jdt.doc.user/tasks/tasks-232.htm?cp=1_3_10_1

So my recommendation would be to:

1. Export the XML format settings (already done in this pull request)
2. Export the settings formatted for the formatting tool (needs to be done), see the 2nd link above.

We can then invoke the following code to mass-format the jgrapht project (only run this within the jgrapht folder...!):

find . -name \*.java -print -exec /opt/eclipse_neon/java_neon/eclipse/eclipse -vm /usr/lib/jvm/java-8-oracle/bin/java -application org.eclipse.jdt.core.JavaCodeFormatter -quiet -config ~/workspace/javaIDEA/jgrapht/etc/eclipse-formatter-settings.txt {} \;

**Comment by jsichi** [comment]
Regarding the line length, I'm biased coming from the days when we used to print out code on paper for code reviews.  But the thing is, code doesn't appear only on giant screens in IDE's.  It also appears in many more constrained places, such as:

* side-by-side visual diffs, where long lines lead to annoying horizontal scrolling
* ssh sessions in a small terminal window
* fixed-width code boxes such as the one above in this pull request, where github had to add a scrollbar to make the long lines from the Eclipse XML accessible

If you feel strongly on this one, let's use 100 (https://www.quora.com/Why-does-Google-Java-coding-style-guide-chose-maximum-of-100-characters-column-limit-per-line-why-not-120-just-curious-to-know)

**Comment by jsichi** [comment]
I'll update the pull-request to add in the command-line-compatible settings file.

**Comment by jkinable** [comment]
Ok, let's go for 100.

**Comment by d-michail** [comment]
If I may suggest, adding a newline after the annotation in the following cases. 

```
<setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_type" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_field" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_method" value="insert"/>
```

Otherwise, when you have more than 1 annotations, it looks kind of strange.

As an example consider 

```
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target(value = { CONSTRUCTOR, FIELD, LOCAL_VARIABLE, METHOD, PACKAGE,
    PARAMETER, TYPE })
public @interface Deprecated
{
}
```

compared to this

```
@Documented @Retention(RetentionPolicy.RUNTIME) @Target(value = { CONSTRUCTOR,
    FIELD, LOCAL_VARIABLE, METHOD, PACKAGE, PARAMETER,
    TYPE }) public @interface Deprecated
{
}
```

**Comment by jsichi** [comment]
OK, I've made the changes discussed above, and re-exported the command-line-compatible format.  One question about the command-line invocation; will it take care of collapsing imports as well?  (I haven't tried it myself yet.)  See https://github.com/jgrapht/jgrapht/wiki/Contributor-Guidelines#eclipse-setup

**Comment by jkinable** [comment]
I just checked, but this:
```
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedList;
```
is not automatically replaced by:
`import java.util.*`

The reason for this seems to be that collapsing import statements in eclipse is not part of the code formatter. I looked into the config files, but there's (afaik) no way to enforce this through the eclipse code formatter. Even in the IDE version there are 2 different commands to format the code and to organize the imports: 
- ctrl+shift+f formats the code
- ctrl+shift+o organizes (and collapses) the imports
so I guess this cannot be done in a single action. 

I haven't used eclipse for several years though (switched to Intellij).

**Comment by jsichi** [comment]
I see.  I searched around and from what I read, there doesn't seem to be a way to do the organize imports step from the command line.  So it sounds like we'll be doing this in the GUI instead.

**Comment by jkinable** [comment]
I couldn't find any automated way to organize java imports either. There are some highly outdated tools, but nothing that seems to work for java 1.8. I submitted an enhancement request for Eclipse. Would be pretty nice if all of this could be done from the command line.

**Pull request merged**
