### PR TITLE
Remove jgrapht-touchgraph

### PR DESCRIPTION
**Pull request by jsichi**

### CODE REVIEW

**Comment by jsichi** [comment]
This also completes the removal of package org.jgrapht.experimental.

**Comment by jkinable** [comment]
I went over this PR: it looks fine to me and I'm happy to merge it.
I agree that that it's annoying that they don't have a maven package (=more work for us), and that the current "experimental" implementation is perhaps not as nice as some of our other exporters in the IO package. However, in the last year we've done a lot of effort to increase the amount of high-quality exporters. So removing an exporter seems almost counter intuitive. From their website it seems that touchgraph is still an actively supported *java* product. If I look at the implementation of this particular converter then I don't think that we loose much by deleting it, but it defines a more general policy. If someone submits a nice touchgraph exporter for the IO package, do we reject it on the basis that touchgraph does not have a maven package?

**Comment by jsichi** [comment]
I don't think we need a general policy prohibiting dependencies which aren't available in Maven Central, although such a lack is certainly one strike against a candidate.  In this case, it's combined with other factors:  

* no evidence of anyone actually using it
* no recent activity on their open source project (the most recent I see is a bulk import of the code to github 5 years ago, with no commits against it; the sourceforge stuff is all ancient)
* confusion around license

If someone does come along with a new adapter, I think the suggestion from Dimitrios of an independent github project would be the best response.

**Comment by jkinable** [comment]
Thanks for the additional clarification. This will come in handy if we need to refer back to this PR in the future.

**Pull request merged**
