### PR TITLE
Preparations for release cycle 1.3.1

### PR DESCRIPTION
**Pull request by jkinable**
Preparations for release cycle 1.3.1

### CODE REVIEW

**Comment by jkinable** [comment]
@d-michail after removing the code you deprecated in the specifics classes, it seems the `SimpleIdentityDirectedGraphTest` broke. Would you mind to have a look?

**Comment by d-michail** [comment]
Fixed!

**Comment by jkinable** [comment]
> Fixed!

Great, thanks. I think this one is ready to be merged.

**Comment by d-michail** [comment]
Thanks!

**Pull request merged**
