### PR TITLE
Optimize isFeasiblePair() and finalize fields

### PR DESCRIPTION
**Pull request by iotamudelta**
Finalize classes and fields were applicable.

Optimize isFeasiblePair() by reordering some if conditions, switching to legacy loops to avoid iterator overhead, and storing intermediates.

This yields in my tests another 10% performance improvement end-to-end. Additionally, he final-ized fields should improve maintainability as their intent is now more clearly captured.

isFeasiblePair remains the biggest hotspot in my test.

----

- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/Become-a-Contributor>
- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/How-to-make-your-first-%28code%29-contribution>
- [ ] I added [unit tests](https://github.com/jgrapht/jgrapht/wiki/Unit-testing)
- [ ] I added [documentation](https://github.com/jgrapht/jgrapht/wiki/How-to-write-documentation)
- [x] I followed the [Coding and Style Conventions](https://github.com/jgrapht/jgrapht/wiki/Coding-and-Style-Conventions)
- [x] I **have not** modified `HISTORY.md` or `CONTRIBUTORS.md`
- [x] I ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)

### CODE REVIEW

**Comment by d-michail** [comment]
We do not use so much `final` in our code base. Definitely not in certain classes which we might extend in the feature. 

I would suggest to add final only where it would really help the compiler produce better code, but not anywhere else.

**Comment by iotamudelta** [comment]
@d-michail that's fair. I've removed the `final` annotations to the VF2 graph/subgraph isomorphism state classes. I've retained it for the `GraphOrdering` for now as that class is not designed to be extended (all fields are `private`) and I would suggest keeping the `final` annotations to the fields also because that'll more properly express their actual use and helped at least me to quicker understand what the algorithm manipulates and what it leaves alone.

Let me know what you think!

**Comment by iotamudelta** [comment]
@d-michail ping :-)

**Comment by d-michail** [comment]
@jsichi any comments on this? Otherwise I will merge.

**Comment by jsichi** [comment]
I'm fine with it.  For non-public classes such as GraphOrdering, there's no harm in marking them final since they couldn't be extended yet anyway (except within the same package).  If we decide to open them up to subclasses later, that means we'll be free to remove final as part of making them public.

In general, declaring final goes well with our recent trend towards functional style within our implementations, so I see it in the same light.

**Comment by d-michail** [comment]
Thanks!

**Pull request merged**
