### PR TITLE
Release cycle 1.5.2

### PR DESCRIPTION
**Pull request by jkinable**
Merge this prior to other PRs.

### CODE REVIEW

**Comment by jkinable** [comment]
1. The following command `mvn -Dmaven.compiler.showWarnings=true -Dmaven.compiler.showDeprecation=true clean compile` fails due to a number of module errors:
```
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/module-info.java:[45,28] requires transitive directive for an automatic module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/alg/flow/MaximumFlowAlgorithmBase.java:[57,45] class org.jgrapht.alg.flow.MaximumFlowAlgorithmBase.VertexExtensionBase in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/alg/flow/MaximumFlowAlgorithmBase.java:[58,45] class org.jgrapht.alg.flow.MaximumFlowAlgorithmBase.AnnotatedFlowEdge in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/alg/flow/MaximumFlowAlgorithmBase.java:[98,27] class org.jgrapht.alg.flow.MaximumFlowAlgorithmBase.VertexExtensionBase in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/alg/flow/MaximumFlowAlgorithmBase.java:[100,26] class org.jgrapht.alg.flow.MaximumFlowAlgorithmBase.AnnotatedFlowEdge in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/alg/flow/MaximumFlowAlgorithmBase.java:[209,36] class org.jgrapht.alg.flow.MaximumFlowAlgorithmBase.AnnotatedFlowEdge in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/alg/cycle/HawickJamesSimpleCycles.java:[95,17] found raw type: java.util.ArrayList
  missing type arguments for generic class java.util.ArrayList<E>
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/alg/isomorphism/IsomorphicGraphMapping.java:[57,9] class org.jgrapht.alg.isomorphism.GraphOrdering in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/alg/isomorphism/IsomorphicGraphMapping.java:[57,33] class org.jgrapht.alg.isomorphism.GraphOrdering in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/alg/isomorphism/VF2AbstractIsomorphismInspector.java:[47,15] class org.jgrapht.alg.isomorphism.GraphOrdering in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/alg/isomorphism/VF2AbstractIsomorphismInspector.java:[47,15] class org.jgrapht.alg.isomorphism.GraphOrdering in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/alg/isomorphism/VF2SubgraphIsomorphismInspector.java:[114,12] class org.jgrapht.alg.isomorphism.VF2SubgraphMappingIterator in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/alg/shortestpath/BaseBidirectionalShortestPathAlgorithm.java:[61,9] class org.jgrapht.alg.shortestpath.BaseBidirectionalShortestPathAlgorithm.BaseSearchFrontier in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/alg/shortestpath/BaseBidirectionalShortestPathAlgorithm.java:[61,51] class org.jgrapht.alg.shortestpath.BaseBidirectionalShortestPathAlgorithm.BaseSearchFrontier in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/traverse/AbstractGraphIterator.java:[45,21] class org.jgrapht.traverse.AbstractGraphIterator.FlyweightEdgeEvent in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/traverse/AbstractGraphIterator.java:[46,21] class org.jgrapht.traverse.AbstractGraphIterator.FlyweightVertexEvent in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/util/SupplierUtil.java:[200,20] serializable class org.jgrapht.util.SupplierUtil.ConstructorSupplier has no definition of serialVersionUID
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/alg/flow/DinicMFImpl.java:[190,23] class org.jgrapht.alg.flow.DinicMFImpl.VertexExtension in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/alg/flow/PushRelabelMFImpl.java:[246,36] class org.jgrapht.alg.flow.MaximumFlowAlgorithmBase.AnnotatedFlowEdge in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/alg/shortestpath/YenShortestPathIterator.java:[549,5] serializable class org.jgrapht.alg.shortestpath.YenShortestPathIterator.YenShortestPathsTree has no definition of serialVersionUID
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/graph/BaseIntrusiveEdgesSpecifics.java:[36,68] class org.jgrapht.graph.IntrusiveEdge in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/graph/WeightedIntrusiveEdgesSpecifics.java:[37,39] class org.jgrapht.graph.IntrusiveWeightedEdge in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/graph/WeightedIntrusiveEdgesSpecifics.java:[48,51] class org.jgrapht.graph.IntrusiveWeightedEdge in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/graph/WeightedIntrusiveEdgesSpecifics.java:[93,15] class org.jgrapht.graph.IntrusiveWeightedEdge in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/alg/isomorphism/VF2GraphIsomorphismInspector.java:[97,12] class org.jgrapht.alg.isomorphism.VF2GraphMappingIterator in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/traverse/ClosestFirstIterator.java:[125,42] class org.jgrapht.traverse.ClosestFirstIterator.QueueEntry in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/traverse/ClosestFirstIterator.java:[169,42] class org.jgrapht.traverse.ClosestFirstIterator.QueueEntry in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/alg/shortestpath/DeltaSteppingShortestPath.java:[220,5] serializable class org.jgrapht.alg.shortestpath.DeltaSteppingShortestPath.MaxEdgeWeightTask has no definition of serialVersionUID
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/graph/UniformIntrusiveEdgesSpecifics.java:[37,39] class org.jgrapht.graph.IntrusiveEdge in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/graph/UniformIntrusiveEdgesSpecifics.java:[48,50] class org.jgrapht.graph.IntrusiveEdge in module org.jgrapht.core is not accessible to clients that require this module
[WARNING] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/org/jgrapht/graph/UniformIntrusiveEdgesSpecifics.java:[72,15] class org.jgrapht.graph.IntrusiveEdge in module org.jgrapht.core is not accessible to clients that require this module
[INFO] 31 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/ANT.AMAZON.COM/kinable/workspace/research/external/jgrapht/jgrapht/jgrapht-core/src/main/java/module-info.java: warnings found and -Werror specified
```
Should this be fixed by updating the `module-info` files?

2. The `VertexDegreeComparator` under `org.jgrapht.alg.util` is no longer a comparator, but more of a wrapper function which provides a comparator by invoking `VertexDegreeComparator.of(graph)`. I don't think this is very clean and would be in favor of making this class an actual comparator again.

**Comment by jsichi** [comment]
Regarding 1, this appears to be the same thing you ran into in #947, and we never did anything to fix those.

**Comment by jkinable** [comment]
Yep, still same issue. Would be great if @io7m could have a look at this, since he helped us out with the initial modularization :).

**Comment by io7m** [comment]
Hello!

The problem here is that non-exported classes appear in the signatures of public methods on classes that _are_ exported. This could happen because you intended to export a class and didn't, but it can also happen because you intended to refer to a class via an exported interface but accidentally referred to the non-exported implementation class instead.

I haven't had time to look at the individual APIs yet, but that's the gist of what's happening here.

**Comment by jsichi** [comment]
I've created issue #1055 for the warnings.

**Comment by jsichi** [comment]
Thanks!

**Pull request merged**
