### PR TITLE
Removed recursion from FibonacciHeap#cascadingCut()

### PR DESCRIPTION
**Pull request by Toptachamann**
Small change in FibonacciHeap#consolidate(): replaced ArrayList with a regular array. The only question is whether an additional warning is acceptable.

----

- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/Become-a-Contributor>
- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/How-to-make-your-first-%28code%29-contribution>
- [x] I added [unit tests](https://github.com/jgrapht/jgrapht/wiki/Unit-testing)
- [x] I added [documentation](https://github.com/jgrapht/jgrapht/wiki/How-to-write-documentation)
- [x] I followed the [Coding and Style Conventions](https://github.com/jgrapht/jgrapht/wiki/Coding-and-Style-Conventions)
- [x] I **have not** modified `HISTORY.md` or `CONTRIBUTORS.md`
- [x] I ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)

### CODE REVIEW

**Comment by Toptachamann** [comment]
Removed the switch from ArrayList to regular array.

**Comment by simlu** [comment]
@Toptachamann Any insight on performance improvements?

**Comment by Toptachamann** [comment]
Here are the performance results. In the setup I generate 1000'000 integers, add them to heaps, remove min on every 10th add so that the heaps are consolidated (this is the only method when consolidate() is invoked). Then in the benchmark methods, I decrease the keys of all nodes to Integer.MIN_VALUE (decreaseKey() is the only method where cuscudingCut() is called).
```
Benchmark                                           Mode   Cnt    Score   Error  Units
FibBenchmark.testIterative                        sample  9329   64.276 ± 0.142  ms/op
FibBenchmark.testIterative:testIterative·p0.00    sample         58.524          ms/op
FibBenchmark.testIterative:testIterative·p0.50    sample         61.866          ms/op
FibBenchmark.testIterative:testIterative·p0.90    sample         68.420          ms/op
FibBenchmark.testIterative:testIterative·p0.95    sample         68.813          ms/op
FibBenchmark.testIterative:testIterative·p0.99    sample         72.352          ms/op
FibBenchmark.testIterative:testIterative·p0.999   sample         95.510          ms/op
FibBenchmark.testIterative:testIterative·p0.9999  sample        115.081          ms/op
FibBenchmark.testIterative:testIterative·p1.00    sample        115.081          ms/op
FibBenchmark.testRecursive                        sample  7543   79.487 ± 0.101  ms/op
FibBenchmark.testRecursive:testRecursive·p0.00    sample         75.891          ms/op
FibBenchmark.testRecursive:testRecursive·p0.50    sample         79.561          ms/op
FibBenchmark.testRecursive:testRecursive·p0.90    sample         82.051          ms/op
FibBenchmark.testRecursive:testRecursive·p0.95    sample         82.575          ms/op
FibBenchmark.testRecursive:testRecursive·p0.99    sample         83.755          ms/op
FibBenchmark.testRecursive:testRecursive·p0.999   sample        107.171          ms/op
FibBenchmark.testRecursive:testRecursive·p0.9999  sample        127.140          ms/op
FibBenchmark.testRecursive:testRecursive·p1.00    sample        127.140          ms/op
```

**Comment by jsichi** [comment]
Seems worth it to me.  Might as well apply this to GenericFibonacciHeap as well?

**Comment by Toptachamann** [comment]
Good point, done.

**Comment by zxp209** [comment]
Hello,everyone:
I have some requests for jgrapht.I have some data edge ,node etc.. I built the graph with following code:

public static WeightedGraph<Integer, Link> create(RoadNetwork roadNetwork) {

    DefaultDirectedWeightedGraph<Integer, Link> graph = new DefaultDirectedWeightedGraph<>(Link.class);

    for(Link link:roadNetwork.getLinks()){
        int sNode = link.getsNode();
        int eNode = link.geteNode();
        graph.addVertex(sNode);
        graph.addVertex(eNode);
        graph.addEdge(sNode,eNode,link);
        graph.setEdgeWeight(link,link.getRoadWeight());
    }

    return graph;
}

 

then I use  DijkstraShortestPath to get shortest path. In our case ,some edges have restrictions. For example:
 

In normal case ,the shortest path is [1,2,3,4,9] but in our case ,path 1-2-3-4-9 is forbidden(like traffic restriction no-return-left).I can’t set the edge(2,3,4) weight infinite ,because another path like 1,5,7,4,9 needs edge 4.
Are there any methods or classes can solve this issue?
 
               Thank you very much!
                       Best regards!

 

 

发件人: bounces+848413-7c56-zxp209=163.com@sgmail.github.com [mailto:bounces+848413-7c56-zxp209=163.com@sgmail.github.com] 代表 Timofey Chudakov
发送时间: 2018年7月19日 15:06
收件人: jgrapht/jgrapht
抄送: Subscribed
主题: Re: [jgrapht/jgrapht] Removed recursion from FibonacciHeap#cascadingCut() (#623)

 

Good point, done.

**Comment by Toptachamann** [comment]
@zxp209 You can open an issue using github issues. Also, could you state the problem more precisely so that it becomes clear whether it can be reduced to single source shortest path problem or not?

**Comment by simlu** [comment]
@jsichi Why are there two (almost identical) implementation with lots of redundant code here? What's the purpose of having GenericFibonacciHeap and FibonacciHeap?

**Comment by jsichi** [comment]
@simlu we started with just the double-specific FibonacciHeap, but then we needed a generic version for other cases (in particular, using BigDecimal for exact arithmetic), so it was copied at that point.  We kept the original for performance.

**Comment by jsichi** [comment]
Thanks @Toptachamann !

**Comment by simlu** [comment]
I'm surprised that there is a significant performance difference. I would have thought with Java compiling to native it doesn't matter? Is this just an assumption or have you tested this?

**Comment by jsichi** [comment]
I don't remember if any perf testing was done at the time; if someone does it now and there's no difference, then it would be nice to get rid of the duplicated code.  

Note that the difference goes a little beyond just generic type+comparators:  the primitive version uses an intrusive approach, putting the responsibility for allocating/managing nodes onto the caller.  This is clunky but allows us to save map lookups.  For an example, see ClosestFirstIterator, where we combine the lookups for the heap nodes with the "seen data" lookups.

The primitive version is used by a bunch of core shortest-path algorithms, so benchmarking scenarios should be based on those usage patterns.

**Pull request merged**
