### PR TITLE
Start release cycle 1.4.1

### PR DESCRIPTION
**Pull request by jkinable**
- Removed deprecated code
- Upgraded java to version 11
- Upgraded plugin versions

### CODE REVIEW

**Comment by jkinable** [comment]
- At some point we should upgrade from junit 4 to junit 5
- It's possible to configure maven to run our junit tests in parallel, which would make sense given the increasing number of tests we run. See https://maven.apache.org/surefire/maven-surefire-plugin/examples/fork-options-and-parallel-execution.html. I'm not sure which options to pick, in particular the forked test vs parallel test.
- The JavaCodeFormatter util in the latest eclipse is broken (https://bugs.eclipse.org/bugs/show_bug.cgi?id=543363). I used an old machine which still had an old version of eclipse installed. Hopefully this gets fixed in the next eclipse release.

**Comment by jkinable** [comment]
@d-michail could you look into the following:

1. DOTExporter.javadoc, lines 216-225 always evaluate to true:
```
if (attributes != null) {
            for (Map.Entry<String, Attribute> entry : attributes.entrySet()) {
                String name = entry.getKey();
                if (name.equals("label")) {
                    // already handled by special case above
                    continue;
                }
                renderAttribute(out, name, entry.getValue());
            }
        }
```
Also, from the class descr it is not clear that the user can set the label attribute, without reading the source code. Maybe we could improve the docs a bit. 

2. SupplierUtil.java, line 65: constructor.isAccessible() is deprecated
3. Fix GraphMLDemo: this still used the old IO classes instead of NIO.
4. Our docs need some updates after moving from IO to NIO: https://jgrapht.org/guide/UserOverview#graph-serialization-and-exportimport

**Comment by jkinable** [comment]
Checkstyle currently fails as I commented out GraphMLDemo. Everything should be good to go after this file has been fixed.

**Comment by d-michail** [comment]
I fixed the demo issues and the DOT exporter. I will update the docs in a separate step.

**Comment by d-michail** [comment]
The doc example that you mention is generated from file `HelloJGraphT` which is already updated. I guess it is a matter of updating the user guide with the newest version.

**Comment by jsichi** [comment]
@d-michail the user guide will get regenerated automatically once this PR is merged

**Comment by jkinable** [comment]
@d-michail could you also look at: SupplierUtil.java, line 65: constructor.isAccessible() is deprecated.

**Comment by d-michail** [comment]
Fixed

**Pull request merged**
