### PR TITLE
CI Maintenance

### PR DESCRIPTION
**Pull request by syoon2**
This PR adds maintenance patches to GitHub Action workflows. This includes:

- Version bump for `actions/checkout` from `v2` (PR workflow) / `v3` (master workflow) to `v4` (refs: https://github.com/actions/checkout/issues/959#issuecomment-1342479774, https://github.com/actions/checkout/pull/1436)
- Version bump for `actions/setup-java` from `v2` (PR workflow) / `v3` (master workflow) to `v4` (refs: https://github.com/actions/setup-java/pull/290, https://github.com/actions/setup-java/pull/558)
- Changing `actions/setup-java` to use Eclipse Temurin build of OpenJDK (was using Azul Zulu OpenJDK)
  Unlike other distributions of OpenJDK, Temurin builds are cached in GH-hosted runners.
- Replacing `actions/cache` for Maven caching with [built-in cache implementation](https://github.com/actions/setup-java#caching-maven-dependencies) in `actions/setup-java`
- Version bump for `JamesIves/github-pages-deploy-action` from `4.1.4` to `v4.5.0`
- Adding [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates) config to automate version updates

----

- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/Become-a-Contributor>
- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/How-to-make-your-first-%28code%29-contribution>
- [ ] <s>I added [unit tests](https://github.com/jgrapht/jgrapht/wiki/Unit-testing)</s> (not applicable)
- [ ] <s>I added [documentation](https://github.com/jgrapht/jgrapht/wiki/How-to-write-documentation)</s> (not applicable)
- [x] I followed the [Coding and Style Conventions](https://github.com/jgrapht/jgrapht/wiki/Coding-and-Style-Conventions)
- [x] I **have not** modified `HISTORY.md` or `CONTRIBUTORS.md`
- [x] I ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)

### CODE REVIEW

**Comment by syoon2** [comment]
Range-diff:
```text
-:  ---------- > 1:  b92c214e1c Fix CRLF/LF Consistency (#1166)
-:  ---------- > 2:  f1c32a530a Credits for last merge.
-:  ---------- > 3:  e625da9351 JUnit 5 Migration (#1163)
-:  ---------- > 4:  9c98ae8a2d Credits for last merge.
1:  a0f8b7b282 = 5:  d9bc9d2d78 Update GitHub Action workflows
2:  a8171ef173 = 6:  d3d9b3ec87 Setup Dependabot
```

@jsichi Mind if I ask for your review?

**Comment by jsichi** [comment]
Thanks, I will just go ahead and merge this and see what happens, since it seems like CI hasn't been running on master for a while anyway, only on PR branches?

**Comment by jsichi** [comment]
(Correction, CI has been running on master correctly; my mistake.)

**Comment by jsichi** [comment]
After merging to master, CI is now failing with "Error: Dependencies lock file is not found in /home/runner/work/jgrapht/jgrapht. Supported file patterns: package-lock.json,npm-shrinkwrap.json,yarn.lock"

See the log here:

https://github.com/jgrapht/jgrapht/actions/runs/7374477613/job/20064905918

**Comment by syoon2** [comment]
Hmm, ouch. Will submit a patch for the regression in the next hour or two.

**Comment by syoon2** [comment]
@jsichi  A side note: Dependabot needs to be manually enabled (because Dependabot is disabled by default on forked repositories) in <https://github.com/jgrapht/jgrapht/network/updates> for it to automatically create dependency update PRs.

**Pull request merged**
