### PR TITLE
Predictable ordering in MaximumCardinalityIterator

### PR DESCRIPTION
**Pull request by d-michail**
This is a PR which attempts to make the vertex ordering of `MaximumCardinalityIterator` predictable. 
This also affects the `ChordalityInspector` and thus also the `ChordalGraphColoring` algorithm which might assign different colors to different vertices based on the different runs. 

@Toptachamann Could you take a look and confirm that there is indeed a problem? Would it be possible to do a similar thing in `LexBreadthFirstIterator`?

----

- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/Become-a-Contributor>
- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/How-to-make-your-first-%28code%29-contribution>
- [x] I added [unit tests](https://github.com/jgrapht/jgrapht/wiki/Unit-testing)
- [x] I added [documentation](https://github.com/jgrapht/jgrapht/wiki/How-to-write-documentation)
- [x] I followed the [Coding and Style Conventions](https://github.com/jgrapht/jgrapht/wiki/Coding-and-Style-Conventions)
- [x] I **have not** modified `HISTORY.md` or `CONTRIBUTORS.md`
- [x] I ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)

### CODE REVIEW

**Comment by Toptachamann** [comment]
All right, I've looked into the code. I'm still not sure why different vertex order across invocations is a problem. In fact, I wasn't able to produce different vertex orders. AFAIK, the current `HashSet` and `HashMap` implementations produce unpredictable but deterministic iteration order (which is not guaranteed but still).

**Comment by d-michail** [comment]
When I say "deterministic" I am not using it in the sense of a Turing machine, I actually mean "predictable". 
I was trying to write a test for another algorithm which depended on the results of this one, and it returned different results every time.

**Comment by Toptachamann** [comment]
So the motivation makes perfect sense to me, the current behaviour is very inconvenient. 

`MaxMaximuimumCardinalityIterator` uses hash container iteration here: `graph.vertexSet()` (lines 84 and 86) and `bucket.iterator().next()` (line 164). The first is deterministic, the second one is fixed by using `LinkedHashSet` as a container for all buckets. So the fix looks good 👍

As for the `LexBreadthFirstIterator`, is it guaranteed that every graph implementation returns a hash container with a predictable iteration order after calling `graph.edgesOf(...)`? I've checked all hash container iterations in `LexBreadthFirstIterator` and this is the only thing that might not be easily fixable.

**Review by Toptachamann — APPROVED** [review]

**Comment by jsichi** [comment]
Is it ok to merge this one now?

**Comment by d-michail** [comment]
@Toptachamann Could you merge this one?

**Comment by Toptachamann** [comment]
Thanks!

**Pull request merged**
