### PR TITLE
Added graph distance metrics

### PR DESCRIPTION
**Pull request by jkinable**
Added Graph distance metrics:

- graph diameter
- graph radius
- vertex eccentricity
- methods to query the graph center and graph periphery

This fixes issues #407 and #406

### CODE REVIEW

**Comment by jkinable** [comment]
There are some other metrics we potentially want to include in the library as well. One of them would be the graph girth, which is defined as the length of the shortest cycle in the graph, or infinity if the graph is acyclic. As far as I know, the girth of a graph is only defined on the number of edges, and not on the actual length (sum of edge weights) of the edges.
Where would you prefer to include a method getGirth(Graph<V,E> graph)? It doesn't really fit in the class `GraphDistanceMetrics`. It could fit in the cycle package, but having a class for a single method like this doesn't seem to make too much sense. Perhaps a new class GraphMetrics in the alg package? This class could return other numerical values, e.g. getChromaticNumber(Graph<V,E> graph). This is perhaps a bad example since the chromatic number is hard to compute.

**Comment by jkinable** [comment]
Preemptively added a method to compute the girth of a graph. See issue mentioned above. I'm not sure what the best place would be for this method, so feel free to make an alternative suggestion. 

Also, Wolfram defines girth as: "The length of the shortest graph cycle (if any) in a graph.". The definition of "shortest cycle" is ambiguous: shortest in terms of edge weights, as in "shortest path", or shortest in terms of least number of edges? I have only encountered cases where girth refers to the cycle with least number of edges

**Comment by jsichi** [comment]
For packaging of GraphMetrics, it seems like it should live in the same package as GraphTests (which is currently in the top-level org.jgrapht package).  Likewise, if it is only static methods, it should be declared abstract.

What's the rationale for distinguishing GraphMetrics from GraphDistanceMetrics?

For GraphDistanceMetrics, since it's a non-static class, the class name should be something non-plural (e.g. GraphMeasurer).

**Comment by jkinable** [comment]
@jsichi I've renamed/moved some of the classes based on your suggestions. The result is indeed cleaner. This PR should be finished now.

**Comment by jkinable** [comment]
This PR is superseded by PR #414

**Pull request closed without merging**
