### PR TITLE
Implement Dijkstra-style all paths algorithm

### PR DESCRIPTION
**Pull request by agdphd**
The `AllDirectedPaths` class implements a Dijkstra-style algorithm for finding all paths in a directed graph from a set of source vertices to a set of target vertices. It offers options to restrict search to paths with no more than a specified number of edges and to restrict to simple (non-self-intersecting) paths.

I have implemented a few test cases, but I'd welcome suggestions for more.

This would address #178.

### CODE REVIEW

**Comment by agdphd** [comment]
Closed and reopened to trigger Travis-CI, which seems to have been napping when I submitted.

**Comment by jsichi** [comment]
Thanks, this gets asked for a lot...now I can't wait for the inevitable issues getting logged about "I tried this on my real-world graph and I got an OOM..."  :)

**Comment by agdphd** [comment]
Glad to help! If it would be useful, I could probably rig up an approach based on Streams that would control the memory consumption, but this would require moving to Java 8.

**Comment by jsichi** [comment]
Yeah we should probably move to Java 8 anyway...maybe after wrapping up the in-progress release.

**Comment by cwensel** [comment]
+1 adopting java 8 after publishing a new version with current changes. Cascading is still used on Hadoop where Java 6 is prevalent (though Cascading 3 is on Java 7 but 8 won't be supported by Hadoop for a bit longer)

**Comment by jsichi** [comment]
OK, 0.9.2 has been released, so I've moved things over to JDK 1.8 on trunk.

**Pull request merged**
