### PR TITLE
Extension of Max Flow algorithms: undirected graphs are now supported

### PR DESCRIPTION
**Pull request by jkinable**
@jsichi : For some reason, this pull request seems to contain a lot of changes I didn't make? E.g. I didn't touch .travis.yml or HISTORY.md? As a result an automatic merge ain't possible. Did I mess something up?

This pull request extends both EdmondsKarpMaximumFlow and PushRelabelMaximumFlow, thereby adding the option to run both algorithms on undirected graphs.

Changelog:
-EdmondsKarpMaximumFlow and PushRelabelMaximimumFlow algorithms now also work on undirected graphs
-Added test for both directed and undirected graphs
-Rewrote & documented significant parts of the old implementation. 
-Deleted RandomizedTest from Max flow tests: this test did not serve any purpose. The results were never verified. The only way the test could fail is if the algorithm throw some internal exception.
-Deleted the Legacy implementation of EdmondsKarpMaximumFlow and corresponding test
-Documented public (!) functions of Extension class. Added some questions wrt revisions.
-Separated flow calculation from actually generating a map representing the flow on each edge individually. The latter often is expensive and unnecessary.

Note: in the previous release of jgrapht, significant changes to the MaxFlow algorithms were introduced. Unfortunately, this code was overly complex, messy, and very poorly documented, especially when you consider the simplicity of the algorithm. It took a considerable amount of time to reverse engineer what was going on. A simple 1 hour task of adding support for undirected graphs turned out to be a 2-day endeavor. Let's try to avoid this in the future. Algorithms should be implemented (and documented) as clear as possible such that other people can extend the code, fix potential bugs, etc. In addition, the runtime complexity of an implementation should be clear.

Note 2: I left several comments in the Extension.java class. Please review those.

### CODE REVIEW

**Comment by jsichi** [comment]
@jkinable I changed those files (e.g. HISTORY.md, where I record the credits for each pull request when I merge it ) via direct commits (instead of via pull requests).  Did that interfere with your workflow somehow?

**Comment by jkinable** [comment]
@jsichi I'm by no means an expert in Git. This is what happened:

1. I synced my master with the master of jgrapht
2. Branched of my master to write the algorithm extension
3. Several changes were made to the jgrapht master, including the java 1.8 clean up pull request and your direct commits
4. I re-synced my master with the master of jgrapht
5. I checked-out my Algorithm extension branch, merged the master branch and resolved a few conflicts. Now my branch should be up-to-date and ready-to-merge with the jgrapht master. But for some reason, it shows a merge conflict. Furthermore, in my algorithm extension branch, I only changed +/-10 files, whereas github states that I changed 319 files! Any idea how this could be fixed?

**Comment by jsichi** [comment]
In the github UI, when I look at your EdmondKarpUndirGraph_releaseCandidate, it tells  me "This branch is 9 commits ahead, 38 commits behind jgrapht:master."  But your master says it is even with jgrapht master.  So looks like something went awry during the merge from your master to your branch.

When this kind of thing happens to me, I usually find the easiest way to clean up is to just create a fresh new branch, copy over the files of interest from the hosed branch, cross myself there times, curse git, and see how things look in a fresh pull request from the new branch.

**Comment by jkinable** [comment]
@jsichi Yep that seems to work. Thanks! I'll close this pull request.

**Pull request closed without merging**
