### PR TITLE
Forest generator based on the Barabási-Albert model

### PR DESCRIPTION
**Pull request by AlexandruValeanu**
I have noticed that I need to generate forests in almost all tests I write so I have implemented a forest generator which is based on the `BarabasiAlbertGraphGenerator`.

### CODE REVIEW

**Comment by jsichi** [comment]
Should probably cross-link this and BarabasiAlbertGraphGenerator via {@link } tags in the Javadoc.

**Comment by AlexandruValeanu** [comment]
Done. Thank you for the idea.

**Comment by d-michail** [comment]
Looks good. @jsichi I am merging this unless there are any more comments.

**Comment by d-michail** [comment]
Thanks!

**Pull request merged**
