### PR TITLE
Test for erroneous DirectedAcyclicGraph#removeAllVertices(...)

### PR DESCRIPTION
**Pull request by besza**
This is a test case for issue #200 . The method as of now incorrectly deletes all information from the topology map even if there vertices left in the graph. Link to the line of code in question: [link](https://github.com/besza/jgrapht/blob/master/jgrapht-core/src/main/java/org/jgrapht/experimental/dag/DirectedAcyclicGraph.java#L358)

My proposal is to change the corresponding method so that it only calls the superclass's implementation of removeAllVertices(...) which in turn removes each vertex one by one mainting the topology order.

If this looks good I can go ahead and fix it in my next commit.

### CODE REVIEW

**Comment by jsichi** [comment]
Based on this warning on removeVertex:

 "note that this can leave holes in the topological ordering, which (depending on the TopoOrderMap implementation) can degrade performance for certain operations over time"

I'm guessing that the intention of the original author was to do something more efficient for the bulk removal case; but he clearly didn't get around to that :)

So I agree with your proposed fix so that it will at least be correct.

**Comment by besza** [comment]
Any idea why the Travis CI build is failing at compile phase? I could build it locally without any problems.

**Comment by d-michail** [comment]
@besza, this is a compilation error, due to a few changes in the graph generators. Try to rebase first.

**Comment by jsichi** [comment]
Thanks!

**Pull request merged**
