### PR TITLE
Issue 876 - Added isEmpty implementation to avoid calculation of size…

### PR DESCRIPTION
**Pull request by omerb4**
… (Complexity O(1) instead of O(n))

----

- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/Become-a-Contributor>
- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/How-to-make-your-first-%28code%29-contribution>
- [x] I added [unit tests](https://github.com/jgrapht/jgrapht/wiki/Unit-testing)
- [x] I added [documentation](https://github.com/jgrapht/jgrapht/wiki/How-to-write-documentation)
- [x] I followed the [Coding and Style Conventions](https://github.com/jgrapht/jgrapht/wiki/Coding-and-Style-Conventions)
- [x] I **have not** modified `HISTORY.md` or `CONTRIBUTORS.md`
- [x] I ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)

### CODE REVIEW

**Comment by Toptachamann** [comment]
1. Could you please make the code style consistent across files? For example, in the MaskVertexSet the braces style is not consistent. In general, I would avoid changing imports style when adding 1 or 2 methods to the file. 

2. As far as I understand, the problem is that the `isEmpty()` method computes the size by filtering the set, which is slow. Code:
``` java
vertexSet.stream().filter(mask.negate()).count() == 0;
```
The current implementation essentially would be:
``` java
!vertexSet.stream().filter(mask.negate()).iterator().hasNext()
```
Does this solution work faster?

**Comment by omerb4** [comment]
Correct, asking hasNext much faster then iterate all values..

**Comment by Toptachamann** [comment]
Okay, now I understand what the difference is. Then the only comment from me would be to revert the code style

**Comment by omerb4** [comment]
Ok, Done.
Please approve and take care of merging it.

**Comment by Toptachamann** [comment]
Thanks!

**Pull request merged**
