### PR TITLE
Implementation of Gabow's algorithm

### PR DESCRIPTION
**Pull request by skomlaebri**
I added a new class with the implementation of the Gabow's algorithm for strongly connected components, that could be used as an alternative to the StrongConnectivityInspector (using Kosaraju's algorithm).

It follows Path-based depth-ﬁrst search for strong and biconnected components by Gabow 
http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.121.839

### CODE REVIEW

**Comment by atombrella** [comment]
Shouldn't the imports be collapsed into single import x.y.*; lines instead of the expanded versions?

**Comment by jkinable** [comment]
Since there has been no activity in this pull request for a long time, I created a followup here:
https://github.com/jgrapht/jgrapht/pull/152
This pull request can now be closed.

**Comment by jsichi** [comment]
Closing as this has been superceded by https://github.com/jgrapht/jgrapht/pull/152

**Comment by jsichi** [comment]
Sarah, thanks for your work on this one...we've included you in the credits for the final pull request submitted by Joris.

**Pull request closed without merging**
