### PR TITLE
Code beautification and interface changes to GmlExporter

### PR DESCRIPTION
**Pull request by d-michail**
- Improved class public interface
- Deprecated old style options
- Fixed not necessary cast when reading edge weights

### CODE REVIEW

**Comment by jkinable** [comment]
@d-michail could you check whether pull request #171 is still necessary and does not conflict with some of the changes you are submitting?

**Comment by jkinable** [comment]
I'm not sure whether I'm really convinced that decomposing the setPrintLabels(final Integer i) and getPrintLabels() into separate functions is an improvement.
I do agree however that setPrintLabels(final Integer i) is quite ugly. My main concerns with the decomposition:
-You have a getter/setter function for every parameter. This results in a rather large amount of functions. Adding potential future parameters requires adding even more functions.
-function names like "isExportVertexLabels()" are quite cumbersome.

I would go for either of the following 2 options:

1. Create an Enum Parameters with all the parameters as originally suggested by @jsichi , and store the values in an EnumMap. Create 2 functions: one setParameter(Parameters param, boolean value) and getParameter(...). So far we have only boolean parameters so that should be nice and concise. If you are concerned with parameters of different types, you can always use something like this: http://stackoverflow.com/questions/24296059/how-do-i-store-enum-types-into-a-map
I wouldn't bother for now.

2. Use a Property map. This is probably the most generic solution, but quite a bit of overkill.

I believe that each time a new version of jgrapht is released, the Jeopardy source code beautifier is executed, so I wouldn't bother too much with making the code pretty by adding/removing spaces. That way, the change set remains nice and small, reducing the review overhead :).

**Comment by d-michail** [comment]
I used boolean parameters under the assumption that these are special parameters and that no new such special parameters would be introduced in the future. As I generally agree with your comments, I changed the implementation to using an enumeration.

Regarding the formatting, I import the etc/eclipse-formatter-settings.xml style into Eclipse. I think Jalopy is quite old and somehow Eclipse and Jalopy produce a slightly different result.

**Comment by jkinable** [comment]
Looks good now. Thanks

**Comment by jkinable** [comment]
Hm, currently there's no description of the parameters anymore. Could you copy the parameter description into the description of the Parameters enum?

**Comment by d-michail** [comment]
Done

**Pull request merged**
