### PR TITLE
Created Stacked book graph generator

### PR DESCRIPTION
**Pull request by mayank097**
I created this graph generator but is facing a small problem in travis ci, hope that you would help me out,

### CODE REVIEW

**Comment by jkinable** [comment]
Please read the [developer guidelines](https://github.com/jgrapht/jgrapht/wiki#developer-pages) and revise your submission accordingly.

**Comment by mayank097** [comment]
the same result were shown in ci servers as the results are in maven,

Lines in which they show error, i find those absolutely fine, really needs
your help here, i am even completed other generators but lagging behind due
to this problem, just need a little push from your side, sir.

**Comment by mayank097** [comment]
please have a

https://travis-ci.org/mayank097/jgrapht

**Comment by jkinable** [comment]
The problem is most likely that you are missing a `)` or `}` or `;`. 

Your code looks very messy. There are many issues with the indentation. Consequently, it is not strange that you run into  such an error. I would recommend using a proper IDE for your code development. Most IDEs are able to automatically detect these errors. To setup an IDE, follow these [guidelines](https://github.com/jgrapht/jgrapht/wiki/How-to-setup-your-development-environment-for-JGraphT).

**Comment by mayank097** [comment]
thank you sir ,  for your help, i will work upon those problems and submit
as soon as possible!.

**Comment by mayank097** [comment]
finally , successfully created Stack graph generator,please have a look and mention if any important thing i missed.

**Comment by mayank097** [comment]
I submitted it with all errors removed, please have a look  ,and tell if i
missed something important, waiting for your views,

Thank you,

**Comment by jkinable** [comment]
You neglected to read any of the links I posted before.... :(

**Comment by mayank097** [comment]
No sir , i was basically worried about that travis ci verification ,  i
read all those and will make it upto you as soon as possible, and sorry for
earlier!!!

**Comment by AlexandruValeanu** [comment]
Try to solve these problems first:

- [ ] Fix indentation (see other implementations)
- [ ] Fix documentation (wrong contributor and author for example
- [ ] Add tests
- [ ] Remove useless commits

**Comment by jkinable** [comment]
As stated before, read the [developer guidelines](https://github.com/jgrapht/jgrapht/wiki#developer-pages) and check for every line whether you did that or not.

**Comment by jkinable** [comment]
Any progress on this one?

**Comment by jkinable** [comment]
Please consider resubmitting a new PR once it's in a complete state. If you have questions/issues, consider asking on our https://groups.google.com/forum/#!forum/jgrapht-dev page, with a link to your personal branch.

**Pull request closed without merging**
