### PR TITLE
Refactored and enhanced functionality of random graph generators

### PR DESCRIPTION
**Pull request by d-michail**
This is an implementation of a random graph generator based on the G(n, p) model.

### CODE REVIEW

**Comment by jkinable** [comment]
Something that we need to emphasize is the difference between this class, and the RandomGraphGenerator class. Both these classes should state something like: "If you want to ..., use <class> instead.", or at least something that clarifies the difference.  Alternatively, would it be possible to have an abstract RandomGraphGenerator class and multiple implementations (a G(n,p) implementation and some class which implements the functionality of the current RandomGraphGenerator class) ?

**Comment by jsichi** [comment]
Yeah, let's deprecate the current RandomGraphGenerator class, renaming it to GnmRandomGraphGenerator.  I don't think there's a good reason to introduce a common abstract base at this point.

**Comment by d-michail** [comment]
Thanks for the suggestions,  I will have a implementation soon. 

@jsichi, @jkinable One more issue that I would like your opinion is about the use of the seed in the  RandomNumberGenerator. 

Currently, the class generates a seed (or receives it as a parameter through the constructor) and then initializes the random number generator every time someone calls the generateGraph method. This way if someone wants to generate 100 (pseudo-)random graphs, the random number generator has to be initialized with 100 different seeds. This is a misuse of the random number generator which is designed to be initialized only once. The generated graphs will also be very dependent  to each other.

I would vote in favor of not initializing the random number generator in every call of the generateGraph but only in the constructor. If someone wants to generate twice the same graph, they can create two instances of the  RandomNumberGenerator with the same seed.

This is actually the reason that the previous implementation had to copy-paste some code from the Random class, since there is no method to read the seed from the random number generator (it is protected).

**Comment by jsichi** [comment]
I agree with only initializing the RNG in the constructor.

**Comment by d-michail** [comment]
Now, I have a first version ready. 

I also took the liberty of implementing the functionality of a random bipartite graph generator (part of which was in the experimental package). The implementation should not be considered experimental, I have added docs and tests where appropriate.

I am not sure about the naming though. I have written one class which is called RandomBipartiteGraphGenerator which contains both the bipartite version of G(n,p) and the bipartite version of  G(n,m). The only difference is the constructor call which is overloaded between a double (probability p) and an integer (edge set size m). Does this look ok, or should I split it into two distinct classes?

**Comment by jsichi** [comment]
Now it's inconsistent between the unpartitioned generators (split into two classes) and the bipartite generator (single class with a profusion of constructors).  I'd say split into two classes for the bipartite generators as well.

**Comment by d-michail** [comment]
Done!

**Comment by jsichi** [comment]
Thanks...there's a conflict now since I just merged Joris' header reformat change, so this pull request will need to be rebased.  As part of that, could you apply etc/HeaderReformat.py to the new files so that they'll match the new format?

**Comment by jkinable** [comment]
Just invoke `python HeaderReformat.py <path to file>` on every _new_ file you created. Sorry for the inconvenience.

**Comment by d-michail** [comment]
ok, I rebased the commits and updated the rest of the headers.

**Comment by jsichi** [comment]
Looks good!

**Pull request merged**
