### PR TITLE
Provide improved transitive closure calculation for DirectedAcyclicGraph

### PR DESCRIPTION
**Pull request by WorstCase00**
I ran into performance issue when calculating the transitive closure for huge DAGs.
Turned out there is a pretty straight-forward algorithm for that as described in the answer here: http://cs.stackexchange.com/questions/7231/efficient-algorithm-for-retrieving-the-transitive-closure-of-a-directed-acyclic

I provided a  new method for DirectAcyclicGraph in the corresponding class.

However the API of this class is a bit weird, since the original method works for SimpleDirectedGraph which is *meant* to not contain cycles, but even the unit tests pass in cyclic graphs.

### CODE REVIEW

**Comment by d-michail** [comment]
Thanks for the code!

Consider also the following refactored variant.

```
public <V, E> void closeDirectedAcyclicGraph(DirectedAcyclicGraph<V, E> graph)
{
    Deque<V> orderedVertices = new ArrayDeque<>(graph.vertexSet().size());
    new TopologicalOrderIterator<>(graph).forEachRemaining(orderedVertices::addFirst);

    for (V vertex : orderedVertices) {
        for (V successor : Graphs.successorListOf(graph, vertex)) {
            for (V closureVertex : Graphs.successorListOf(graph, successor)) {
                graph.addEdge(vertex, closureVertex);
            }
        }
    }
}
```

`SimpleDirectedGraph` may contain cycles, it does not contain self-loops which are edges with same source and target vertices.

**Comment by WorstCase00** [comment]
Thanks for your feedback @d-michail !
I updated the PR based on your feedback after reading up about the advantages of ArrayDeque (which I haven't been aware of). 
... and of course it's also the more elegant solution.

Cheers

**Comment by jkinable** [comment]
@d-michail are you happy with the pull request? If so, could you merge it, then I'll finish this release cycle.

**Comment by d-michail** [comment]
@WorstCase00 After the main branch latest updates, there is a branch conflict which needs resolving. 

Moreover, as we keep a changelog with contributions, could you provide your full name? If you prefer not to, we will use the github username.

**Comment by WorstCase00** [comment]
@d-michail Thanks, I just resolved the conflict.
My full name is Martin Sturm.
Cheers

**Comment by d-michail** [comment]
Thanks!

**Pull request merged**
