### PR TITLE
Handle maxPathLength=1 case correctly in AllDirectedPaths

### PR DESCRIPTION
**Pull request by agdphd**
Fixes an edge case in initializing the algorithm when maxPathLength=1, resolving #441.

### CODE REVIEW

**Comment by jsichi** [comment]
Hi Andrew,

We're ready to merge this one, but before we do, just wanted to verify (since you added Google LLC to the authorship):  you have permission from Google to be contributing under LGPL+EPL dual license, right?

**Comment by agdphd** [comment]
Thanks for checking in! Yes, Google's policies for contributing patches to open-source projects on GitHub are pretty liberal these days, and what I'm doing here is in compliance. (See https://opensource.google.com/docs/patching/#patches-that-dont-require-any-review if you're interested in the details.)

**Comment by jsichi** [comment]
Awesome, thanks!  @d-michail go ahead and merge when ready.

**Comment by d-michail** [comment]
Thanks!

**Pull request merged**
