### PR TITLE
Algorithm for finding simple cycles described by Hawick and James

### PR DESCRIPTION
**Pull request by lzkill**
Here's a implementation of the algorithm for finding simple cycles described by Hawick and James.

K. A. Hawick, H. A. James. Enumerating Circuits and Loops in Graphs with Self-Arcs and Multiple-Arcs. Computational Science Technical Note CSTN-013, 2008.

### CODE REVIEW

**Comment by atombrella** [comment]
I looked over the guidelines for contributing, and one thing that your code violates is explicit import, instead of 

    import java.util.*;
    import org.jgrapht.*;

**Comment by lzkill** [comment]
Well, the implicit imports brake it...

**Comment by atombrella** [comment]
-import org.jgrapht.alg.cycle.DirectedSimpleCycles;
    +
    +import java.util.*;
    +import org.jgrapht.*;

You also need this:

    import org.jgrapht.alg.*;

**Comment by jsichi** [comment]
Thanks!

**Pull request merged**
