### PR TITLE
Fixed Suurballe non-deterministic output

### PR DESCRIPTION
**Pull request by assimiz**
----
This is fixing issue [#943](https://github.com/jgrapht/jgrapht/issues/943).
Problem was with the stitching of the paths fragments to valid paths. Edges should be taken from the paths in FIFO method. So, if we are currently at node `u` and we have two outgoing edges from it - `(u, v)` and `(u, w)`, we should take the edge discovered earlier (i.e. for the lowest `k` path). So now order of validEdges is preserved so providing deterministic output.

- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/Become-a-Contributor>
- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/How-to-make-your-first-%28code%29-contribution>
- [x] I added [unit tests](https://github.com/jgrapht/jgrapht/wiki/Unit-testing)
- [x] I added [documentation](https://github.com/jgrapht/jgrapht/wiki/How-to-write-documentation)
- [x] I followed the [Coding and Style Conventions](https://github.com/jgrapht/jgrapht/wiki/Coding-and-Style-Conventions)
- [x] I **have not** modified `HISTORY.md` or `CONTRIBUTORS.md`
- [x] I ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)

### CODE REVIEW

**Comment by d-michail** [comment]
Consider using `ArrayDeque` to get the best of both worlds. You can remove from both ends without shifting and still get the array benefits.

**Comment by jsichi** [comment]
Hi @assimiz, we had a configuration error which caused your PR build attempt to fail; sorry about that.  Could you merge from master to pick up the fix for that (25c5ccf231fc07fc4b0cf47e8c18e67e56fe6498)?

**Comment by assimiz** [comment]
@d-michail I need to remove only from start of list, never from the end of it. Also not pushing to it only polling so linked list is satisfying here I think.

**Comment by d-michail** [comment]
You are missing the point!

The `ArrayDeque` is much faster, since it uses an circular buffer array underneath, and thus has much better cache locality in modern architectures.

I am fully aware that you only remove from the beginning. I only mentioned that for extra information. Maybe you encounter this again in the future.

**Comment by jsichi** [comment]
For the performance reason @d-michail noted, and for consistency with the rest of the codebase (https://github.com/jgrapht/jgrapht/pull/889), please switch to ArrayDeque.

**Comment by jsichi** [comment]
Thanks, I've confirmed that this fixes the original testcase as well.

**Pull request merged**
