### PR TITLE
ability to accumulate data in every path

### PR DESCRIPTION
**Pull request by mdorfman**
This feature allows user data accumulation in each path. 
User can create multiple accumulators for different data types. 
RankingPathElement will accumulate each data type separately. 
Optionally validation can be defined. Then the accumulated data will be checked for each new edge.
As result of the validation the path might be dropped.

### CODE REVIEW

**Comment by jsichi** [comment]
Hi Masha,

Please use the standard header for all files (it includes both LGPL and EPL).  If this code is being contributed as part of employment by AT&T, the attribution should be " by AT&T and Contributors" (not "AT&T Intellectual Property").  And if that's the case, could you please also confirm here that you've been given permission by the company to contribute under both licenses?

Thanks!

**Comment by mdorfman** [comment]
Hi John,
I asked permission for EPL only and have this permission.
I'll do another call for LGPL.

Thanks


Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by jkinable** [comment]
Hi Masha,
Thank you for your code submission. I just went over your code and the changes you are proposing for the `KShortestPath` implementation. The `PathAccumulator` proposed in this PR 'accumulates' information about the partial paths maintained by the `KShortestPath` algorithm. Each time a partial path p is about to be extended with a new edge e, the `PathAccumulator` checks whether this extension is feasible, based on (1) the accumulated information for path `p`, (2) the 'costs/resource requirements' of edge `e` and (3) some limit maintained by the `PathAccumulator`. 
In essence, the already existing `PathValidator` does the same: it checks whether a partial path p, represented as a `GraphPath`, can be extended with a new edge e. The difference is that the `PathValidator` does not 'accumulate' information. Instead one would have to iterate over the edges in partial path `p` to obtain the same information (which, arguably, is less efficient).
Finally, `KShortestPath` uses yet another (3rd) mechanism to handle resource constraints, namely directly in the `KShortestPath` iterator. See for instance how the algorithm limits the number of hops in a path.

In summary, unless I'm misinterpreting something, this PR introduces a 3rd mechanism in `KShortestPath` to do essentially the same thing: putting resource constraints on a shortest path. Finally, looking at the implementation of `PathAccumulator`: the class frequently replicates itself, and will have a rather significant performance impact when it is used on a large graphs. Consequently I'm proposing not to merge this PR. I'll leave this PR open for the author and potential other reviewers to respond.


While taking a closer look at the `KShortestPath` implementation, it would be good to drastically revise the implementation of this algorithm. I would recommend to use the implementation of a Label-Setting shortest path problem as the basis for this algorithm (as a starting point, see for instance Network Flows by Ahuja et al.; there exist several papers which discuss highly optimized data structures for Label Setting algorithms). A Label-Setting algorithm is the basis for many Elementary Shortest Path problems with Resource Constraints. This would allow us to have 1 mechanism to deal with resource constraints (relatively similar to the Accumulator in this PR), and we could also add a mechanism to establish path domination. Moreover, the resulting code would be cleaner, more concise and significantly faster than the current `KShortestPath` implementation.

**Comment by mdorfman** [comment]
Hi Joris,
Thank you for the analysis. I will try to protect this PR ☺ I’ll refer to the current implementation rather than to future algorithm improvements.
For now I implemented several types of constraints on application layer using PathValidator callback.

Regarding PathValidator solution.
“In essence, the already existing PathValidator does the same: it checks whether a partial path p, represented as a GraphPath, can be extended with a new edge e. The difference is that the PathValidator does not 'accumulate' information. Instead one would have to iterate over the edges in partial path p to obtain the same information (which, arguably, is less efficient).”

·        Path Validator can be seen as a private case of Path Accumulator. As you mentioned Path Validator doesn’t accumulate information, so it doesn’t need replication.

·        When accumulation is required to resolve constraint on large graphs, two solutions might be compared from performance perspective : repeated end-to-end analysis of each candidate path on each new edge addition. Vs. replication of accumulator object on each new edge addition [m(m+1)/2 updates vs. m replications]. As you said its arguable.

·        Additional point is amount of concurrent constraints. I have multiple ones and more are going to be added in future. On each PathValidator invocation an application has two options

o   either it goes over end-to-end prevPath for each constraint calculation.

o   or it goes once over prevPath but calculates all the constraints at once on each step.

o   Former means increase of #loops, latter – all calculations run and are analyzed in parallel. In order to prepare minimal framework for future constraints it needs encapsulation similar to what I suggested in this PR. I have such framework for now on app level

Regarding number of hops in a path solution.
“Finally, KShortestPath uses yet another (3rd) mechanism to handle resource constraints, namely directly in the KShortestPath iterator. See for instance how the algorithm limits the number of hops in a path”

·        Let us look at weight solution as an example. Weight is accumulated over paths. Weight is set by user explicitly edge by edge [setEdgeWeight()]. Also accumulation is explicit in RankingPathElementList. Weight is numerical and its accumulation is implemented as “+”. Weight is used to order paths. If in future the algorithm decides to have multiple weights, it also will need to order the resulting paths.

The point is that weight solution currently is not capsulated and cannot be used or extended by user application.

o   Application cannot add additional constraints in parallel.

o   Application might have constraints which are not numeric.

o   Application might have constraints which do not need ordering but rather require just hard limit or another validations. For example you may want to minimize latency while not exceed certain amount of hops. And vice versa.

If algorithm is going to be changed, it will be great to implement also ability to validate accumulated information of any type, per user choice.

Thanks,
Masha Dorfman

**Pull request closed without merging**
