### PR TITLE
Issue 875 - Allow overriding BFS SeenData externally

### PR DESCRIPTION
**Pull request by omerb4**
----

- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/Become-a-Contributor>
- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/How-to-make-your-first-%28code%29-contribution>
- [x] I added [unit tests](https://github.com/jgrapht/jgrapht/wiki/Unit-testing)
- [x] I added [documentation](https://github.com/jgrapht/jgrapht/wiki/How-to-write-documentation)
- [x] I followed the [Coding and Style Conventions](https://github.com/jgrapht/jgrapht/wiki/Coding-and-Style-Conventions)
- [x] I **have not** modified `HISTORY.md` or `CONTRIBUTORS.md`
- [x] I ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)

### CODE REVIEW

**Comment by Toptachamann** [comment]
Looks good! I'm going to merge this in a couple of days unless there're more comments

**Comment by Toptachamann** [comment]
Thanks! Could you, please, let me know your real name so that I can add you to the History.md?

**Comment by omerb4** [comment]
@Toptachamann Can you publish a new release?

**Comment by jsichi** [comment]
We don't perform releases for each change, but you can use the SNAPSHOT release instead, which is published automatically.

**Comment by omerb4** [comment]
> Thanks! Could you, please, let me know your real name so that I can add you to the History.md?

Omer Biran

**Pull request merged**
