### PR TITLE
K disjoint paths null pointer bug fix

### PR DESCRIPTION
**Pull request by bkrogh**
Identified a bug causing null pointer exceptions in k disjoint shortest path algorithms. Added a minimal test case that triggers the bug in both Suur. Implemented bug fixes in code.
[#790](https://github.com/jgrapht/jgrapht/issues/790)

----

- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/Become-a-Contributor>
- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/How-to-make-your-first-%28code%29-contribution>
- [x] I added [unit tests](https://github.com/jgrapht/jgrapht/wiki/Unit-testing)
- [x] I added [documentation](https://github.com/jgrapht/jgrapht/wiki/How-to-write-documentation)
- [x] I followed the [Coding and Style Conventions](https://github.com/jgrapht/jgrapht/wiki/Coding-and-Style-Conventions)
- [x] I **have not** modified `HISTORY.md` or `CONTRIBUTORS.md`
- [x] I ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)

### CODE REVIEW

**Comment by d-michail** [comment]
Please make sure that no code formatting changes are in the PR. This way, reviewers can identify the actual changes easily.

**Comment by bkrogh** [comment]
> Please make sure that no code formatting changes are in the PR. This way, reviewers can identify the actual changes easily.

To the best of my knowledge, there are no code formatting changes in this PR?
I am likely simply misunderstanding what you mean. Would you mind providing an example to me on where I made an error?

**Comment by d-michail** [comment]
Hit the "Files Changed" tab and you will see.

**Comment by bkrogh** [comment]
> Hit the "Files Changed" tab and you will see.

You are right! I was careful not to hit any auto format, but I must have done so inadvertently anyway. Sorry for the confusion.

I have made a new PR without formatting changes. I am therefore closing this PR.

**Pull request closed without merging**
