### PR TITLE
Changed queue implementation from LinkedList to ArrayDeque for better performance

### PR DESCRIPTION
**Pull request by rtkg12**
Fixes jgrapht/jgrapht#809
Changed all found implementations of queues to ArrayDeque.

----

- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/Become-a-Contributor>
- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/How-to-make-your-first-%28code%29-contribution>
- [x] I added [unit tests](https://github.com/jgrapht/jgrapht/wiki/Unit-testing)
- [x] I added [documentation](https://github.com/jgrapht/jgrapht/wiki/How-to-write-documentation)
- [x] I followed the [Coding and Style Conventions](https://github.com/jgrapht/jgrapht/wiki/Coding-and-Style-Conventions)
- [x] I **have not** modified `HISTORY.md` or `CONTRIBUTORS.md`
- [x] I ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)

### CODE REVIEW

**Comment by jsichi** [comment]
Unless anyone has objections, I'll merge this one in a few days, assuming the world still exists then.

**Comment by jsichi** [comment]
Also, @rtkg12 could you tell us your real name for the credits?

**Comment by rtkg12** [comment]
It's Ritik Goyal. Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shevek** [comment]
hooray! thank you. i like performance.

**Comment by jsichi** [comment]
Thanks!

**Pull request merged**
