### PR TITLE
Composition of binary relations implemented

### PR DESCRIPTION
**Pull request by vporton**

### CODE REVIEW

**Comment by d-michail** [comment]
Before any official review of the code, let me comment on a fundamental issue.

When we write similar code in JGraphT we use generics for both the graph vertices and graph edges.
Since you need to be able to create a new graph and/or edges, you have two options
 - you provide an instance of the target graph also as a parameter
 - or you provide an `EdgeFactory`

In the first case the method would look like
```
static <V,E> void compose(Graph<V, E> b, Graph<V, E> a, Graph<V,E> target);
```

in the second case the method looks like
```
static <V,E> Graph<V, E> compose(Graph<V, E> b, Graph<V, E> a, EdgeFactory<V,E> edgeFactory);
```

I am probably in favor of the first form. @jkinable, @jsichi Preferences?

**Comment by vporton** [comment]
I tried to make the edge type generic. But I found this impossible:

Suppose the edge type is generic. Then we need to provide "composition" function for the edges.

But for DefaultEdge this is impossible, because `getSource()` and `getTarget()` of a DefaultEdge are not public. Therefore we cannot write a generic method which could compose two DefaultEdge objects.

**Comment by d-michail** [comment]
The graph interface has a `getEdgeSource(E)` and a `getEdgeTarget(E)` method. All accesses to the source and target of an edge must happen using these methods. I would suggest to look around at the library in order to understand the way that we write the algorithms. 

Your implementation is fine for your specific application, but at the "library level" all implementations must happen using the graph API.

Following on my previous comment, the following works:

```
 public static <V, E> void compose(Graph<V, E> b, Graph<V, E> a, Graph<V, E> target)
    {
        for (V x : a.vertexSet()) {
            Set<E> edges1 = a.outgoingEdgesOf(x);
            for (V z : b.vertexSet()) {
                for (E e1 : edges1) {
                    final V y = a.getEdgeTarget(e1);
                    if (b.containsEdge(y, z)) {
                        Graphs.addEdgeWithVertices(target, x, z);
                        break;
                    }
                }
            }
        }
    }
```

**Comment by vporton** [comment]
@d-michail I have followed your advice and pushed a new version.

**Comment by jkinable** [comment]
I agree with @d-michail : consistent with our graph importer classes, I would prefer to use:
`static <V,E> void compose(Graph<V, E> b, Graph<V, E> a, Graph<V,E> target);`

Another issue, prior to reviewing, is the following. JGraphT is a graph library. New contributions should in general be useful for multiple users, not just for one individual project. In this particular case, I have mixed feelings about whether we should include this into the library. I'm not an expert on function compositions or set theory, but it this is not a typical item encountered in graph theory. Instead, graphs (as a datastructure) can be used to model relations. This however is more of an example of a specific application domain (in comparison, several common problems in computational biology can be modeled on a graph, but there's no biology package in jgrapht either). @d-michail what do you think?
If we do include something like this, I would recommend to make a more generic class which covers common "function compositions"/"set theory" operations which are performed on a graph, instead of just a single "compose"  method.
Finally, we would have to make sure that users in need of this functionality, are actually able to find this particular implementation. Currently, I don't think that this will be possible.

**Comment by vporton** [comment]
Relation of composition is encountered in mathematics **very** often. It is surely worth to be included in JGraphT.

**Comment by vporton** [comment]
For example composition of relations may be used to calculate transitive closure (yes, I know it is already implemented):

* new X = X united with compose(X, X);
* return X if old X = new X.

**Comment by jsichi** [comment]
We're lacking consensus on this being a good fit for JGraphT in its current form, so closing this one out. Take a look at this doc for other options:

https://github.com/jgrapht/jgrapht/wiki/Become-a-Contributor#plan-b

**Pull request closed without merging**
