### PR TITLE
Checker for Bergeness of arbitrary simple undirected graphs

### PR DESCRIPTION
**Pull request by PhilippKaesgen**
Proposed class tests arbitrary simple undirected graphs for Bergeness, i.e. whether they are perfect

### CODE REVIEW

**Comment by jsichi** [comment]
All files need the standard JGraphT header.

Also, all classes need corresponding unit tests.

**Comment by jkinable** [comment]
@PhilippKaesgen any updates on this? It would pity to abandon this pull request because there are no unit tests.

**Comment by PhilippKaesgen** [comment]
Sorry. I've been really busy with my thesis for the last couple of months. I'll take care of this when I have some spare time.

**Comment by jkinable** [comment]
Any updates wrt this PR? We are getting close to the next release. The first submission of this PR is now 1.5 years old. It would be unfortunate to tag this PR as abandoned.

**Comment by PhilippKaesgen** [comment]
Recently I adapted the files to the 1.0 release and wrote more unit tests. Yet, I have to make sure that the program is compliant with the definition of perfect graphs - occasionally, the checker still outputs wrong results. I also had contact with Chudnovsky to sort out some details about the underlying definitions and mathematical proofs. I expect that this will take me several more months (It is a leisure project of mine, though). It's your decision whether to tag the PR as abandoned or not, but that's all I can offer right now.

**Comment by jkinable** [comment]
@PhilippKaesgen any updates? It would still be nice to have an isBerge(Graph<> g) method :)

**Comment by jkinable** [comment]
@PhilippKaesgen any new updates? It would be great if we could wrap up this PR.

**Comment by jkinable** [comment]
What happened? :(

**Pull request closed without merging**
