### PR TITLE
chore(deps): Update dependencies

### PR DESCRIPTION
**Pull request by reneleonhardt**
I updated all dependencies where possible, but had to exclude `javax.mail` and disable `<failOnWarning>`, they have to be fixed/suppressed later.
Checkstyle configuration for `JavadocMethod` changed in 8.42 (`scope` has been replaced by `accessModifiers`).

----

- [x ] I read and understood <https://github.com/jgrapht/jgrapht/wiki/Become-a-Contributor>
- [ x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/How-to-make-your-first-%28code%29-contribution>
- [ x] I added [unit tests](https://github.com/jgrapht/jgrapht/wiki/Unit-testing)
- [ x] I added [documentation](https://github.com/jgrapht/jgrapht/wiki/How-to-write-documentation)
- [ x] I followed the [Coding and Style Conventions](https://github.com/jgrapht/jgrapht/wiki/Coding-and-Style-Conventions)
- [ x] I **have not** modified `HISTORY.md` or `CONTRIBUTORS.md`
- [ x] I ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)

### CODE REVIEW

**Comment by jsichi** [comment]
Thanks for centralizing the version number dependencies.  We usually do the upgrade step right after a release to give the updates lots of time to flush out any issues; see step 18 in https://github.com/jgrapht/jgrapht/blob/master/etc/ReleaseProcess.md

We can do the upgrade now too, but we need to do an extraneous dependency check first.  I ran through the before-and-after for the dependencies.  Here's the before:

```
jvs@havnor:~/tmp/jgrapht-1.5.2-SNAPSHOT/lib$ ll
total 34888
-rw-rw-r-- 1 jvs jvs   322137 Mar 13 20:28 antlr4-runtime-4.10.1.jar
-rw-rw-r-- 1 jvs jvs   556428 Mar 21  2022 apfloat-1.10.1.jar
-rw-rw-r-- 1 jvs jvs   587402 Mar 13 20:28 commons-lang3-3.12.0.jar
-rw-rw-r-- 1 jvs jvs  2213560 Nov 28  2020 commons-math3-3.6.1.jar
-rw-rw-r-- 1 jvs jvs   238400 Mar 13 20:28 commons-text-1.10.0.jar
-rw-rw-r-- 1 jvs jvs   515555 Feb  2  2021 dsiutils-2.6.17.jar
-rw-rw-r-- 1 jvs jvs 23504030 Feb  2  2021 fastutil-8.5.2.jar
-rw-rw-r-- 1 jvs jvs  2874025 Mar 21  2022 guava-30.1.1-jre.jar
-rw-rw-r-- 1 jvs jvs  1267457 Mar 13 20:37 jgrapht-core-1.5.2-SNAPSHOT.jar
-rw-rw-r-- 1 jvs jvs    36625 Mar 13 20:37 jgrapht-demo-1.5.2-SNAPSHOT.jar
-rw-rw-r-- 1 jvs jvs     5957 Mar 13 20:37 jgrapht-ext-1.5.2-SNAPSHOT.jar
-rw-rw-r-- 1 jvs jvs    47121 Mar 13 20:37 jgrapht-guava-1.5.2-SNAPSHOT.jar
-rw-rw-r-- 1 jvs jvs   366121 Mar 13 20:37 jgrapht-io-1.5.2-SNAPSHOT.jar
-rw-rw-r-- 1 jvs jvs    38604 Mar 13 20:37 jgrapht-opt-1.5.2-SNAPSHOT.jar
-rw-rw-r-- 1 jvs jvs    88046 Mar 13 20:37 jgrapht-unimi-dsi-1.5.2-SNAPSHOT.jar
-rw-rw-r-- 1 jvs jvs   832332 Mar 21  2022 jgraphx-4.2.2.jar
-rw-rw-r-- 1 jvs jvs   153258 Mar 22  2021 jheaps-0.14.jar
-rw-rw-r-- 1 jvs jvs    90009 Feb  2  2021 jsap-20210129.jar
-rw-rw-r-- 1 jvs jvs   290339 Nov 28  2020 logback-classic-1.2.3.jar
-rw-rw-r-- 1 jvs jvs   471901 Nov 28  2020 logback-core-1.2.3.jar
-rw-rw-r-- 1 jvs jvs    41472 Nov 28  2020 slf4j-api-1.7.30.jar
-rw-rw-r-- 1 jvs jvs   455212 Feb  2  2021 sux4j-5.2.3.jar
-rw-rw-r-- 1 jvs jvs   383933 Feb  2  2021 webgraph-3.6.10.jar
-rw-rw-r-- 1 jvs jvs   296349 Feb  2  2021 webgraph-big-3.6.6.jar
```

And here's the after:

```
jvs@havnor:~/tmp/reneleonhardt/jgrapht/jgrapht-dist/target/jgrapht-1.5.2-SNAPSHOT/lib$ ll
total 35616
-rw-rw-r-- 1 jvs jvs    62983 Mar 13 20:56 activation-1.1.jar
-rw-rw-r-- 1 jvs jvs   322137 Mar 13 20:28 antlr4-runtime-4.10.1.jar
-rw-rw-r-- 1 jvs jvs   556428 Mar 21  2022 apfloat-1.10.1.jar
-rw-rw-r-- 1 jvs jvs   587402 Mar 13 20:28 commons-lang3-3.12.0.jar
-rw-rw-r-- 1 jvs jvs  2213560 Nov 28  2020 commons-math3-3.6.1.jar
-rw-rw-r-- 1 jvs jvs   238400 Mar 13 20:28 commons-text-1.10.0.jar
-rw-rw-r-- 1 jvs jvs   518451 Mar 13 20:56 dsiutils-2.7.3.jar
-rw-rw-r-- 1 jvs jvs 23326598 Mar 13 20:55 fastutil-8.5.12.jar
-rw-rw-r-- 1 jvs jvs  2959479 Mar 13 20:55 guava-31.1-jre.jar
-rw-rw-r-- 1 jvs jvs   659031 Mar 13 20:56 javax.mail-1.6.2.jar
-rw-rw-r-- 1 jvs jvs  1267513 Mar 13 20:55 jgrapht-core-1.5.2-SNAPSHOT.jar
-rw-rw-r-- 1 jvs jvs    36625 Mar 13 20:56 jgrapht-demo-1.5.2-SNAPSHOT.jar
-rw-rw-r-- 1 jvs jvs     5962 Mar 13 20:55 jgrapht-ext-1.5.2-SNAPSHOT.jar
-rw-rw-r-- 1 jvs jvs    47153 Mar 13 20:55 jgrapht-guava-1.5.2-SNAPSHOT.jar
-rw-rw-r-- 1 jvs jvs   366089 Mar 13 20:55 jgrapht-io-1.5.2-SNAPSHOT.jar
-rw-rw-r-- 1 jvs jvs    38631 Mar 13 20:55 jgrapht-opt-1.5.2-SNAPSHOT.jar
-rw-rw-r-- 1 jvs jvs    88050 Mar 13 20:56 jgrapht-unimi-dsi-1.5.2-SNAPSHOT.jar
-rw-rw-r-- 1 jvs jvs   832332 Mar 21  2022 jgraphx-4.2.2.jar
-rw-rw-r-- 1 jvs jvs   153258 Mar 22  2021 jheaps-0.14.jar
-rw-rw-r-- 1 jvs jvs    90009 Feb  2  2021 jsap-20210129.jar
-rw-rw-r-- 1 jvs jvs   260451 Mar 13 20:56 logback-classic-1.3.4.jar
-rw-rw-r-- 1 jvs jvs   563976 Mar 13 20:56 logback-core-1.3.4.jar
-rw-rw-r-- 1 jvs jvs    61409 Mar 13 20:56 slf4j-api-2.0.3.jar
-rw-rw-r-- 1 jvs jvs   480589 Mar 13 20:56 sux4j-5.4.1.jar
-rw-rw-r-- 1 jvs jvs   383933 Feb  2  2021 webgraph-3.6.10.jar
-rw-rw-r-- 1 jvs jvs   303687 Mar 13 20:56 webgraph-big-3.7.0.jar
```

The two items of concern are:

* activation-1-1.jar
*  javax.mail-1.6.2.jar

I'm sure we don't want javax.mail, and activation got dragged in by that as well.  So need to add an exclusion somewhere to keep those out.

**Comment by reneleonhardt** [comment]
No problem, i can revert the upgrade commit in this branch.
Just for you to double-check I will add the exclusions here too.

**Comment by reneleonhardt** [comment]
A version without updates (no second commit) is here now, if that would be easier to merge: #1147 @jsichi

**Comment by jsichi** [comment]
I merged #1147.  If you want to rebase off of that, I can merge this one two now that you've added the exclusions.

@jkinable said he can start working on a release towards the end of this month.

**Comment by reneleonhardt** [comment]
Thank you, I rebased and changed the comment @jsichi

I am very glad to hear it, we desperately need a new release for migrating our project to Spring Boot 3 because some security bugs won't get fixed in Spring 5!

**Comment by reneleonhardt** [comment]
Is there still something else needed? @jsichi
Maybe it's better to build a release without those updates here first if it's possible, the ANTLR update is the most important one, we need it :)

**Comment by jsichi** [comment]
@jkinable what do you think?

**Comment by reneleonhardt** [comment]
Are there reservations against releasing the master? @jsichi @jkinable
The last tag was 2 years ago, an updated dependency stack is needed for current apps :)

**Comment by jsichi** [comment]
Apologies, @jkinable got delayed but he's going to try for next week.

**Comment by jsichi** [comment]
Great, merging now, thanks!

**Comment by reneleonhardt** [comment]
@jkinable Thank you, can the community help to make the Maven release process easier, is there an area which would have a large impact if improved?
I will try to help with the Maven warnings after the release, but it will probably require code changes and should be tested longer than version upgrades.

**Comment by jkinable** [comment]
@reneleonhardt A new release (jgrapht-1.5.2) is now available via maven. Official announcement will follow later once we finish updating the website.

**Pull request merged**
