### PR TITLE
Preparation for release cycle 1.5.1

### PR DESCRIPTION
**Pull request by jkinable**
- updated versions dependencies
- removed deprecated code

Please merge this one first prior to merging other PRs.

### CODE REVIEW

**Comment by jkinable** [comment]
It seems there's still a module issue, as the following command terminates with errors:
`mvn -Dmaven.compiler.showWarnings=true -Dmaven.compiler.showDeprecation=true clean compile`
Mostly: class XYZ in module org.jgrapht.core is not accessible to clients that require this module

**Comment by jsichi** [comment]
Grrr...#946 should have caught this, but it seems that just adding  

`-Dmaven.compiler.showWarnings=true`

somehow enables more warnings?

**Comment by jsichi** [comment]
To suppress these, you can add the following after -Xlint:all in the root pom.xml:

`-requires-automatic,-requires-transitive-automatic,-serial,-exports,-rawtypes`

until we review and fix each one.

**Comment by jsichi** [comment]
@jkinable do you want me to go ahead and merge, and then we can do a separate PR to fix the warnings?  I think all the module ones are spurious because they're complaining about package-private classes, which can't be accessed by callers anyway, so I'm not sure what the point of the warning is.

**Comment by jkinable** [comment]
yes, let's go ahead and merge. Not sure why there are module warnings
related to package-private classes.

**Comment by jsichi** [comment]
OK thanks!

**Pull request merged**
