### PR TITLE
Bhandari K Shortest paths: Improved findOverlappingEdges efficiency.

### PR DESCRIPTION
**Pull request by assimiz**
This is fixing issue #577. I took different approach than suggested there as the working graph cannot be reference for the existence of an edge, nor the edge `hashCode `case it exist indeed. Two edges are considered as overlapping case both resides between the same ends disregarding direction. Due to the transformations the graph is going through at the `prepare `method (edges are added and removed) the `hashCode `may be different for two overlapping edges so cannot be used as the criterion. That's why I used edge to edge comparison in the first implementation. 
Current implementation is building a Multigraph from all paths edges and then identifies all overlapping edges so doing pratically the same while having the linear running time suggested in #577.

### CODE REVIEW

**Comment by jsichi** [comment]
For the purpose of detecting overlapping edges, can't you just refer to the original graph instead of the working graph, and then Joris' suggested code should work?

**Comment by jsichi** [comment]
Regarding the hash codes, you can probably make use of class org.jgrapht.alg.util.UnorderedPair as your key instead of edge objects; that will also simplify the logic for detecting reverse edges.

**Comment by assimiz** [comment]
Referring to the original graph would miss those edges exist in the working as in some cases the edge would be found in the working and in others it would be found in the original. 
However, we do not need it as the UnorderedPair only cares about the edge ends (which always exist in both graphs).

**Comment by jsichi** [comment]
Two r's in occurrence.

**Comment by jsichi** [comment]
Thanks!

**Pull request merged**
