### PR TITLE
Add EdgeBetweennessCentrality algorithm

### PR DESCRIPTION
**Pull request by EdwinOuwehand**
Having an EdgeBetweennessCentrality algorithm is a prerequisite for implementing the Girvan–Newman algorithm (community detection) as mentioned on collaboration ideas wiki page. It includes a new interface and some unit tests. 

----

- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/Become-a-Contributor>
- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/How-to-make-your-first-%28code%29-contribution>
- [x] I added [unit tests](https://github.com/jgrapht/jgrapht/wiki/Unit-testing)
- [x] I added [documentation](https://github.com/jgrapht/jgrapht/wiki/How-to-write-documentation)
- [x] I followed the [Coding and Style Conventions](https://github.com/jgrapht/jgrapht/wiki/Coding-and-Style-Conventions)
- [x] I **have not** modified `HISTORY.md` or `CONTRIBUTORS.md`
- [x] I ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)

### CODE REVIEW

**Comment by EdwinOuwehand** [comment]
@FabianLockhorst

**Comment by jsichi** [comment]
Please add standard headers to all files.  Travis CI should have flagged this, so there's something broken in our automated enforcement; I'll look into that.

**Comment by jsichi** [comment]
I've fixed the checkstyle configuration in https://github.com/jgrapht/jgrapht/commit/055fde77205a0bebfd8d24a4e7788889017f0406.

**Comment by EdwinOuwehand** [comment]
> Please add standard headers to all files. Travis CI should have flagged this, so there's something broken in our automated enforcement; I'll look into that.

Ah my mistake, all done now.

**Review by d-michail — COMMENTED** [review]
Hi Edwin, 

after briefly looking at the implementation, three points need addressing. 

a) It seems you only support the unweighted case. Supporting the weighted case means to use a priority queue instead of a FIFO queue in the implementation of the single-source shortest paths. We use the jheaps library for such priority queues, thus you can find many examples in the library.

b) A very nice paper which contains the final "accumulation" is the following: 
Ulrik Brandes: On Variants of Shortest-Path Betweenness Centrality and their Generic Computation. Social Networks 30(2):136-145, 2008
See Algorithm 7.

c) Most such algorithms need some normalization at the end. At the very least you need to perform a division by 2 in case the graph is undirected, since your scores are twice as large.

Take a look at our vertex betweenness centrality implementation.

**Comment by d-michail** [comment]
Closing (see #1032)

**Pull request closed without merging**
