### PR TITLE
Remove recursion from DAG.dfsF and dfsB methods

### PR DESCRIPTION
**Pull request by gilles-gosuin**
https://github.com/jgrapht/jgrapht/issues/556

### CODE REVIEW

**Comment by d-michail** [comment]
Thanks! I will try to have a quick look shortly. Could you replace the `LinkedList` with an `ArrayDeque` instead. We usually use this as it exhibits better cache locality.

**Comment by d-michail** [comment]
My only concern here is that vertices can be in the stack simultaneously multiple times (which is normal). Thus, we should probably include a is-visited check after pop and skip the loop. 

I guess something like 
```
if (visited.getVisited(topoIndex))
    continue;
```
would do the job. @jsichi Opinion?

**Comment by jsichi** [comment]
@d-michail wouldn't it be better to just do visited.setVisited at the time we push a vertex?  That would match the existing recursive sequencing, and avoid redundant stack entries.

**Comment by d-michail** [comment]
@jsichi I think that such a modification would make the traversal non-dfs. An interesting blog post which discusses this is the [following](https://11011110.github.io/blog/2013/12/17/stack-based-graph-traversal.html).

Maybe it makes sense in our particular case, I am not sure. However, just checking for visited status after the pop is fine.

**Comment by jsichi** [comment]
I agree about the terminology; but in this case, I believe the algorithm is just trying to find the reachable subgraph, and it doesn't care about the variety of traversal.  That's why the original recursive code is able to mark each vertex visited immediately as it encounters it.

So yeah, either do the post-pop check for terminological precision, or else do the pre-push marking and change the method name to reachable instead.

**Comment by d-michail** [comment]
@gilles-gosuin Could you fix the last remaining issue as suggested?

**Comment by d-michail** [comment]
Thanks!

**Comment by gilles-gosuin** [comment]
Glad I could help :)

**Pull request merged**
