### PR TITLE
Fixed NullPointerException when no path exists in DijkstraManyToManyShortestPaths

### LINKED ISSUE #1053: DijkstraManyToManyPaths throws NullPointerException in the "reversed" case when no path exists
```
 * JGraphT version: 1.5.1
 * Java version (java -version)/platform:  11
```

**Issue**
Accordin to the javadoc, DijkstraManyToManyShortestPaths.getManyToManyPaths.getPath(source, sink) is supposed to return the shortest path from source to sink _or null if there is no path_.

However, a NullPointerException is thrown if the set of target vertices is larger than the set of source vertices and no path between a given source and a given target vertex exists.

**Steps to reproduce (small coding example)**
        var directedGraph = new DefaultDirectedGraph<String, DefaultEdge>(DefaultEdge.class);
        directedGraph.addVertex("a");
        directedGraph.addVertex("b");
        directedGraph.addVertex("c");
        var dijkstra = new DijkstraManyToManyShortestPaths<>(directedGraph);
        var paths = dijkstra.getManyToManyPaths(Set.of("a"), Set.of("b", "c"));

        paths.getPath("a", "b"); // throws NullPointerException

**Expected behaviour**
paths.getPath("a", "b") returns `null`

**Other information**

### PR DESCRIPTION
**Pull request by d-michail**
Fixes #1053 

----

- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/Become-a-Contributor>
- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/How-to-make-your-first-%28code%29-contribution>
- [x] I added [unit tests](https://github.com/jgrapht/jgrapht/wiki/Unit-testing)
- [x] I added [documentation](https://github.com/jgrapht/jgrapht/wiki/How-to-write-documentation)
- [x] I followed the [Coding and Style Conventions](https://github.com/jgrapht/jgrapht/wiki/Coding-and-Style-Conventions)
- [x] I **have not** modified `HISTORY.md` or `CONTRIBUTORS.md`
- [x] I ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)

### CODE REVIEW

**Comment by delta-peg** [comment]
Wow, thanks for the express fix! I will move to the snapshot build once it's on master.

**Comment by d-michail** [comment]
@jkinable Do not forget to merge this one, before the release.

**Comment by jkinable** [comment]
I unfortunately completed the release yesterday night. This one will be the first in line for the next release :). We need to merge PR #1051 before this one can be merged.

**Comment by jsichi** [comment]
Thanks!

**Pull request merged**
