### PR TITLE
Preparing release cycle jgrapht 1.0.2

### PR DESCRIPTION
**Pull request by jkinable**
- Deleted all deprecated code from the previous release
- Removed dependencies on the deprecated Assert class and some other generic cleanup

### CODE REVIEW

**Comment by jkinable** [comment]
@d-michail there are 2 deprecated functions left in AbstractBaseGraph, which have been introduced in pull request #309 What should I do with those?

**Comment by d-michail** [comment]
Two options: 
  - Either adjust to private and remove the `Deprecated` annotation, or 
  - inline them in the `createSpecifics()` method and remove them completely.

Subclasses can specialize the specifics by overriding directly the `createSpecifics()`.

**Comment by jkinable** [comment]
alright done. feel free to merge this one.

**Comment by d-michail** [comment]
Thanks for the release and cleaning up the code!

**Pull request merged**
