### PR TITLE
Enforcing correct javadoc through travis

### PR DESCRIPTION
**Pull request by jkinable**
Currently, Travis does not check javadoc. Since jdk8, the rules for correct javadoc became more strict. It would be great if our contributors fix javadoc issues in their own classes. To enforce this, I propose to enforce this through travis. 

I'm not sure how to do this correctly though, so this is a bit experimental.
Currently, travis executes:
```
mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V 
mvn test -B
```
I'm not sure why travis needs a separate command for the tests. I think it could have exectued:
```
mvn install -DskipTests=false -Dmaven.javadoc.skip=true -B -V 
```
but I guess there's a good reason for this. Hence I've modified the script accordingly.
Alternatively, I guess that this would work as well:
`script: mvn clean install -Dmaven.javadoc.skip=false -B -V`
Not sure which one is better, the one in the pull request, or the line above.

### CODE REVIEW

**Comment by d-michail** [comment]
@jkinable, one other possible way is to use [checkstyle](http://checkstyle.sourceforge.net/) which also has a [maven plugin](https://maven.apache.org/plugins/maven-checkstyle-plugin/usage.html).

**Comment by jkinable** [comment]
hm, would checkstyle cause travis to fail if it detects errors? That would
be desirable, otherwise there's probably not much incentive for a
contributor to get things fixed (and I absolutely dislike fixing javadoc
issues....).
Would using checkstyle as opposed to forcing travis to build the javadoc
through mvn provide some advantage?

I have no strong (or even a weak) opinion about which solution to use
exactly, so I'm happy to go with what you and @jsichi think is best. From
the release doc (
https://rawgit.com/jgrapht/jgrapht/master/etc/release-process.html), it
seems we used checkstyle somewhere in the past.

On Thu, Sep 15, 2016 at 1:00 PM, Dimitrios Michail <notifications@github.com

**Comment by jkinable** [comment]
hm, seems to be something wrong with the command (see travis log). Any suggestions as what could be wrong?

**Comment by jsichi** [comment]
Maybe something weird with the way travis interprets the backslash continuation character?  Maybe try it all on one line instead?

**Comment by jsichi** [comment]
It's preferable to verify the javadoc generation directly via mvn, instead of going through checkstyle as an intermediary.  Otherwise we might hit discrepancies where checkstyle allows something but the build still fails when we attempt to make a release.

Separately, bring back checkstyle for other purposes might still be useful (e.g. equals vs == is one of our perennial problems).

**Comment by jkinable** [comment]
This seems to work. I still haven't figured out whether we need:
`mvn install -DskipTests=false -Dmaven.javadoc.skip=false -B -V`
or
`mvn install -DskipTests=true -Dmaven.javadoc.skip=false -B -V && mvn test -B`
or
`mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V && mvn test -B && mvn javadoc:aggregate`

The travis log now correctly shows that javadoc is generated.

**Comment by jsichi** [comment]
It should be possible to intentionally break Javadoc in this pull request and verify that Travis fails (then fix the Javadoc), right?

Likewise for tests.

**Comment by d-michail** [comment]
Pull request #284 contains a small suggestion on how to enable checkstyle and fail the build using a maven profile called "checkstyle". 

Not necessarily to be included in the Travis build, but probably useful during development.

**Comment by jkinable** [comment]
Alright, I've tested all 3 variations of the script command I stated above, and only the last one works according to expectations. As you can see from the commit history, I broke some stuff on purpose which resulted in a number of expected travis fails. 

Unless you have any further remarks, I think this one is ready to merge.

**Comment by jsichi** [comment]
Nice!

**Pull request merged**
