### PR TITLE
Modules support

### PR DESCRIPTION
**Pull request by d-michail**
A first attempt in adding modules. Two main problems: 

 - We have some test-jar dependencies, which complicate things considerably. I solved this by 
   duplicating the two test utility classes. If someone has more time to invest on this, please fix this. 
 - The bundle package, complicates things, I had to also add a module there, but it is currently 
   empty which means that it might not work correctly. 

I would be in favor of completely removing the uberjar, no point keeping it together with modules.

@io7m would be great to get feedback from you on this!

----

- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/Become-a-Contributor>
- [x] I read and understood <https://github.com/jgrapht/jgrapht/wiki/How-to-make-your-first-%28code%29-contribution>
- [x] I added [unit tests](https://github.com/jgrapht/jgrapht/wiki/Unit-testing)
- [x] I added [documentation](https://github.com/jgrapht/jgrapht/wiki/How-to-write-documentation)
- [x] I followed the [Coding and Style Conventions](https://github.com/jgrapht/jgrapht/wiki/Coding-and-Style-Conventions)
- [x] I **have not** modified `HISTORY.md` or `CONTRIBUTORS.md`
- [x] I ensured that [the git commit message is a good one](https://github.com/joelparkerhenderson/git_commit_message)

### CODE REVIEW

**Comment by d-michail** [comment]
@jsichi Any point in keeping the bundle jar? We should also probably remove the Automatic-Module-Name.

**Comment by d-michail** [comment]
Checkstyle does not even support module-info files! Added the proper exclusions. 

At this point, it should build and pass all phases. However two things need to be resolved: 
  - what do we do with the bundle package? Do we list all shaded classes in the module (no!) ? Do we completely remove it (yes!) 
  - there is one more error `no reactor project: org.jgrapht:jgrapht-dist` which does not seem to affect the build. 

@io7m Do we need to remove the automatic entry in the manifests?

**Comment by jsichi** [comment]
I hear you loud and clear.  Let's nuke the bundle, mention it in the release notes, and see if anyone notices.  If they do, we'll figure out how to bring it back in a followup release.

**Comment by jkinable** [comment]
Can't recall the last time I used the bundle package. Especially not since
maven makes it so convenient to pull in dependencies. So I don't mind to
see bundle go.

Joris

**Comment by d-michail** [comment]
It should be usable now. Could you try locally?

**Comment by jsichi** [comment]
mvn test => works
mvn verify => works
mvn install => works
mvn javadoc:aggregate => works
mvn -DdryRun=true deploy => works (and after unpacking the distribution, the generated javadoc shows nice modules, and even has a working search, which means #884 might go away)
mvn source:jar => works
mvn javadoc:jar => fails as below (same for both JDK 11 and 14)

```
[INFO] ------------------------------------------------------------------------
[INFO] Building JGraphT - Core 1.4.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-javadoc-plugin:3.2.0:jar (default-cli) @ jgrapht-core ---
[INFO] No previous run data found, generating javadoc.
[INFO] 
Loading source file /home/jvs/open/d-michail/jgrapht/jgrapht-core/src/main/java/module-info.java...
1 error
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JGraphT - Parent ................................... SUCCESS [  0.844 s]
[INFO] JGraphT - Core ..................................... FAILURE [  0.829 s]
[INFO] JGraphT - I/O ...................................... SKIPPED
[INFO] JGraphT - Optimized Graphs ......................... SKIPPED
[INFO] JGraphT - Ext ...................................... SKIPPED
[INFO] JGraphT - Guava Adapter ............................ SKIPPED
[INFO] JGraphT - Demo ..................................... SKIPPED
[INFO] JGraphT - Distributable Archives ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.268 s
[INFO] Finished at: 2020-06-06T18:07:35-07:00
[INFO] Final Memory: 16M/64M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:jar (default-cli) on project jgrapht-core: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - error: module not found: org.jgrapht.core
[ERROR] 
[ERROR] Command line was: /usr/java/jdk/bin/javadoc --allow-script-in-comments @options @packages @argfile
```

mvn -DdryRun=true release:prepare => fails as below

```
    Loading source file /home/jvs/open/d-michail/jgrapht/jgrapht-core/src/main/java/module-info.java...
    1 error
    [INFO] ------------------------------------------------------------------------
    [INFO] Reactor Summary:
    [INFO] 
    [INFO] JGraphT - Parent ................................... SUCCESS [  3.429 s]
    [INFO] JGraphT - Core ..................................... FAILURE [03:14 min]
    [INFO] JGraphT - I/O ...................................... SKIPPED
    [INFO] JGraphT - Optimized Graphs ......................... SKIPPED
    [INFO] JGraphT - Ext ...................................... SKIPPED
    [INFO] JGraphT - Guava Adapter ............................ SKIPPED
    [INFO] JGraphT - Demo ..................................... SKIPPED
    [INFO] JGraphT - Distributable Archives ................... SKIPPED
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 03:18 min
    [INFO] Finished at: 2020-06-06T18:01:50-07:00
    [INFO] Final Memory: 32M/117M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.7:jar (attach-javadocs) on project jgrapht-core: MavenReportException: Error while creating archive:
    [ERROR] Exit code: 1 - /home/jvs/open/d-michail/jgrapht/jgrapht-core/src/main/java/module-info.java:42: error: module not found: org.jheaps
    [ERROR] requires transitive org.jheaps;
    [ERROR] ^
    [ERROR] 
    [ERROR] Command line was: /usr/java/jdk/bin/javadoc --allow-script-in-comments @options @packages @argfile
    [ERROR] 
    [ERROR] Refer to the generated Javadoc files in '/home/jvs/open/d-michail/jgrapht/jgrapht-core/target/apidocs' dir.
```

**Comment by d-michail** [comment]
I am a little out of my depth here. Unless I start digging inside the maven-javadoc-plugin, I cannot really tell what is going on. Hope for @io7m to step in!

**Comment by io7m** [comment]
Hello!

Taking a look at this now...

**Comment by io7m** [comment]
I'm seeing the same errors right up to and including JDK 14. I can't work out why these errors are occurring. Paging @rfscholte... :smile:

**Comment by rfscholte** [comment]
`Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.7:jar`. This is not the most recent version of the plugin, see https://maven.apache.org/plugins/index.html

**Comment by jsichi** [comment]
In the errors above, mvn javadoc:jar reports the correct plugin version (3.2.0) but still fails.

For mvn release:prepare, we are using v2.5.1 of maven-release-plugin, so I guess that is accidentally dragging in an old version of maven-javadoc-plugin?  We can try upgrading maven-release-plugin.

**Comment by rfscholte** [comment]
try `mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:effective-pom -Dverbose` to see what pulls in this version

**Comment by jsichi** [comment]
I tried that (output in https://pastebin.com/nA5ES3Gw) but it doesn't mention 2.7 anywhere; all the maven-javadoc-plugin references say 3.2.0.  So I am still guessing it is implicit from the old maven-release-plugin version.  I am going to try with the latest version of that and see what happens.

**Comment by jsichi** [comment]
Weird...even with 3.0.0-M1 for maven-release-plugin (and for maven-deploy-plugin just in case), I still see 2.7 for the maven-javadoc-plugin version from dryRun release.  We don't reference this version anywhere.

**Comment by d-michail** [comment]
Upgraded all plugin versions just in case, but still seeing the same errors. Any chance this is related with some parent pom (oss-7)?

**Comment by olamy** [comment]
what exact jdk version are you using? And which vendor Oracle, Openjdk?
yup some issues has been fixed in openjdk but not backported in Oracle...
I would try with last openjdk11

**Comment by d-michail** [comment]
Not sure for the others, but I am using `openjdk11`, `openjdk14` and `graalvm20`. The same error occurs in all three cases.

**Comment by olamy** [comment]
but which version?

**Comment by d-michail** [comment]
opendk11 is 
```
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)
```

openjdk13 is 
```
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```
and graalvm is
```
java 11.0.6 2020-01-14 LTS
Java(TM) SE Runtime Environment GraalVM EE 20.0.0 (build 11.0.6+8-LTS-jvmci-20.0-b02)
Java HotSpot(TM) 64-Bit Server VM GraalVM EE 20.0.0 (build 11.0.6+8-LTS-jvmci-20.0-b02, mixed mode, sharing)
```

**Comment by jsichi** [comment]
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7)
OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

java version "11.0.6" 2020-01-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)

**Comment by jsichi** [comment]
My maven installation was old (3.3.9), so I upgraded to latest, but failures are still the same.

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/jvs/apache-maven-3.6.3
Java version: 14.0.1, vendor: Oracle Corporation, runtime: /usr/java/jdk-14.0.1
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-143-generic", arch: "amd64", family: "unix"

**Comment by jsichi** [comment]
@d-michail you are right about the parent pom!  When I remove the parent tag altogether, release:prepare runs through successfully (it doesn't even mention javadoc anywhere).  release:perform also works (well, it doesn't do much for dryRun).

However, javadoc:jar is still failing in the same way (module not found: org.jgrapht.core).  I guess that's not surprising since it was already using the correct version.

**Comment by rfscholte** [comment]
`mvn -N help:effective-pom -Dverbose -Psonatype-oss-release` shows you the following:

```
<plugin>
        <artifactId>maven-javadoc-plugin</artifactId>  <!-- org.sonatype.oss:oss-parent:7, line 125 -->
        <version>2.7</version>  <!-- org.sonatype.oss:oss-parent:7, line 126 -->
        <executions>
          <execution>
```
So yes, oss-parent is responsible for 2.7 and you should overwrite it in your root pom.

**Comment by jsichi** [comment]
@rfscholte thanks a lot for your help!

We already have the maven-javadoc-plugin version specified explicitly as 3.2.0 in our root pom.  That effective-pom command output contains two entries; one for 3.2.0 (wrapped in a plugins tag under a pluginManagement tag, the way we have it in our pom) and one for 2.7 (in a separate plugins tag, with no enclosing pluginManagement tag).

What's the correct way to override the parent?

**Comment by jsichi** [comment]
Adding a top-level plugins entry like this (keeping the existing pluginManagement untouched) seems to work:

```
<build>
  <plugins>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-javadoc-plugin</artifactId>
      <version>3.2.0</version>
     </plugin>
  </plugins>
  <pluginManagement>
...
```

Now we're left with just the javadoc:jar failure.

**Comment by olamy** [comment]
yup sounds like a real javadoc failure
Can you try 
`mvn org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:javadoc`
I get 
```
Loading source file /Users/olamy/dev/sources/maven/tmp/jgrapht/jgrapht-core/src/main/java/module-info.java...
1 error
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for JGraphT - Parent 1.4.1-SNAPSHOT:
[INFO] 
[INFO] JGraphT - Parent ................................... SUCCESS [  1.086 s]
[INFO] JGraphT - Core ..................................... FAILURE [  0.971 s]
[INFO] JGraphT - I/O ...................................... SKIPPED
[INFO] JGraphT - Optimized Graphs ......................... SKIPPED
[INFO] JGraphT - Ext ...................................... SKIPPED
[INFO] JGraphT - Guava Adapter ............................ SKIPPED
[INFO] JGraphT - Demo ..................................... SKIPPED
[INFO] JGraphT - Distributable Archives ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.391 s
[INFO] Finished at: 2020-06-09T07:24:44+10:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:javadoc (default-cli) on project jgrapht-core: An error has occurred in Javadoc report generation: 
[ERROR] Exit code: 1 - error: module not found: org.jgrapht.core
[ERROR] 
[ERROR] Command line was: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/javadoc --allow-script-in-comments @options @packages @argfile
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/Users/olamy/dev/sources/maven/tmp/jgrapht/jgrapht-core/target/site/apidocs' dir.
```

**Comment by jsichi** [comment]
Yes, I get the same error.  What's the cause?  javadoc:aggregate is working fine.

**Comment by d-michail** [comment]
@jsichi Could you test? Even with dry-run it asks for credentials.

**Comment by jsichi** [comment]
Working fine now.  @joris note the updated release process; let's say that `mvn javadoc:jar` will be "the one that got away" for now since `mvn package` will take care of that step.  Let me know if I should go ahead and merge.

**Comment by jkinable** [comment]
Would it be possible to summarize this PR:

- any issues that were not fixed in this PR and should be addressed in the future? Any other compromises?
- are we future proof (for the time being) in terms of module support?

Currently it seems we only ditched the bundle package. 

@io7m could you briefly go over the module changes in this PR and see whether you can spot any obvious issues?

**Comment by jkinable** [comment]
@d-michail we ditched the bundle package: do we still need the mvn bundle plugin in the root pom?

**Comment by d-michail** [comment]
The bundle package and the bundle plugin have nothing to do with each other. They only share a common name. The bundle package was build using the shade plugin.

**Comment by jkinable** [comment]
@jsichi let's go ahead and merge this one. Then I can retry the release.
@d-michail Would it be possible to summarize this PR:

- any issues that were not fixed in this PR and should be addressed in the future? Any other compromises?
- are we future proof (for the time being) in terms of module support?

@io7m if you find a bit of time, even after the merge of this PR, please let us know if you see any remaining issues or have any other concerns.

**Comment by jsichi** [comment]
OK, I'm gonna merge now.  @jkinable I'll send you a message soon when it's all clear to retry the release...I am going to take care of #940 and #946 first.

Big thanks to @io7m @rfscholte @olamy for your assistance with this one!

**Pull request merged**
